package typy_bazowe;

/**
 * Created by gadzik on 26.12.19.
 */
public enum TypKategoria {
    GLOBAL_PLANSZA,
    LUDZIE, /*PRACA,*/ MIEJSCA, TYP_LUDZI,
    WYMAGANIA_WSTEPNE, WYMAGANIA_UTRZYMANIA, WARUNKI_KONCOWE,
    SWIAT, INFORMACJA, WIEDZA, BRAKWSTYDU, REZULTAT, PRACA, PRACA_RESTRYKCYJNA, ZARABIANIE, SPORT, OSIEDLE, DOPUSZCZENIE, KOBIETA,
    PRZYCZYNY_ZLA, PRZYCZYNY_DOBRA,
    WARTOSC, OCENIA_WEDLUG,
    THREAD_WHILE_LOOP,
    PRZEWAGI, SLABOSCI,
    CIERPIENIE,
    ZASADY, ZAGROZENIA, POTRZEBA, PRZYMUS, NIESPRAWIEDLIWOSC, OSLONA,
    DOBRY, ZLY,
    WYMUSZENIE_REAKCJI, REAKCJA,
    SONDA, SONDA_GDY, SONDA_PO,
    PLAN, ERA,
    ZART, ROZRYWKI,
    EMOCJE, EMOCJE_POZYTYWNE, EMOCJE_NEGATYWNE,
    UCZUCIA, UCZUCIA_POZYTYWNE, UCZUCIA_NEGATYWNE,
    ZDOBYWANIE_WIEDZY,
    ZAROBEK_NIELEGALNY, KURESTWO,
    KRYTERIA, KRYTERIA_PRZYPALU, KRYTERIA_WROGA,
    TERROR,
    FEST, DZIALAJACY, DZIALAJACY_ZNAKI_ROZPOZNAWCZE,
    BLAD, KOGO,
    HIERARCHIA, HIERARCHIA_ULICA, HIERARCHIA_PRACA,
    CYKL_DNIA,
    KSZTALTOWANIE, KSZTALTOWANIE_CZLOWIEKA, KSZTALTOWANIE_DZIELNICY,
    SPEDZANIE_CZASU,
    RANY, RANY_PSYCHICZNE, RANY_FIZYCZNE, RANY_ZNECANIE_SIE, RANY_SPRZET, RANY_DOSTEPOWE, KTO_KOGO, STARCIE,
    TYP_PRACY, PRACA_FIZYCZNA, PRACA_HANDEL, PRACA_WYMAGAJACA_UMIEJETNOSCI, PRACA_USLUGI, PRACA_OSWIATA,
    PRACA_TRANSPORT, PRACA_TECHNICZNA_UMYSLOWA,
    NASTAWIENIE



    ,
    PATOLOGIA,
    PATOLOGIE_ZWIAZKU,
    PATOLOGIE_WSTEPNE_SWIAT, PATOLOGIE_WSTEPNE_INFORMACJA, PATOLOGIE_WSTEPNE_WIEDZA, PATOLOGIE_WSTEPNE_BRAK_WSTYDU,
    PATOLOGIE_WSTEPNE_REZULTAT, PATOLOGIE_WSTEPNE_PRACA, PATOLOGIE_WSTEPNE_ZARABIANIE, PATOLOGIE_WSTEPNE_SPORT,
    PATOLOGIE_WSTEPNE_OSIEDLE, PATOLOGIE_WSTEPNE_DOPUSZCZENIE, PATOLOGIE_WSTEPNE_KOBIETA, PATOLOGIE_UTRZYMANIA_SWIAT,
    PATOLOGIE_UTRZYMANIA_INFORMACJA, PATOLOGIE_UTRZYMANIA_WIEDZA, PATOLOGIE_UTRZYMANIA_BRAK_WSTYDU,
    PATOLOGIE_UTRZYMANIA_REZULTAT, PATOLOGIE_UTRZYMANIA_PRACA, PATOLOGIE_UTRZYMANIA_ZARABIANIE,
    PATOLOGIE_UTRZYMANIA_SPORT, PATOLOGIE_UTRZYMANIA_OSIEDLE, PATOLOGIE_UTRZYMANIA_KOBIETA,
    PATOLOGIE_KONCOWE_SWIAT, PATOLOGIE_KONCOWE_PRACA, PATOLOGIE_KONCOWE_ZARABIANIE,
    PATOLOGIE_KONCOWE_SPORT, PATOLOGIE_KONCOWE_OSIEDLE, PATOLOGIE_KONCOWE_KOBIETA,
    PATOLOGIE_GLOBAL_PLANSZA_LUDZIE, PATOLOGIE_GLOBAL_PLANSZA_PRACA, PATOLOGIE_THREAD_WHILE_LOOP
}
