package typy_bazowe;

/**
 * Created by gadzik on 28.12.19.
 */
public enum TypMiejsce {
    MIASTO, CENTRUM_MIASTA, DZIELNICA,
    PRZYSTANEK, TRAUTO,
    PRACA_BUDYNEK, SKLEP, LUMPEX, LODY, RESTAURACJA,
    PARKING, STACJA_BENZYNOWA, POCZTA, BANK,
    MIESZKANIE, SZKOLA, STUDIA,
    SAMOCHOD, KOSCIOL, DOM,
    WAKACJE, IMPREZY,

    OSIEDLOWE_SRD,
    WAKACJE_POLSKA, DOBRE_KLUBY_1_STRONA, MECZ_1_STRONA,

    _x5, _x3, _x2
}
