package typy_bazowe;

/**
 * Created by gadzik on 20.12.19.
 */
public enum TypOsoby {
    STATYSTA, LOKALNY, TURYSTA_ZAGRANICZNY,

    STARY, MLODY, SREDNI_WIEK,

    FEST, BANAN, SYSTEMOWY_BURZUJ, WYGODNIS, BURZUJ_NIESWIADOMY, BURZUJ_DZIALACZ,
    OSIEDLOWY_BURZUJ, OSIEDLOWY_WYKRECONY, OSIEDLOWY_CASUAL, SPORTOWY_FEST,
    OSIEDLOWY_NORMAL, OSIEDLOWY_OGARNIETY,
    BIEGACZ, PATOLOG, DIL, ZLODZIEJ,
    WIECZNY_IMIGRANT,
    RDZENNY_GLUPI, RDZENNY_DOBRY,

    CZORT, OSIEDLOWA_KARYNA, OSIEDLOWA_KSIEZNICZKA, OSIEDLOWA_AGRESORKA, OSIEDLOWA_NORMALNA, OSIEDLOWA_DOBRA, OSIEDLOWA_SWIATOWA,
    BURZUA, KUJONKA, ZBYT_WRAZLIWA, ZWYKLA_FEST, WIESNIARA,
    SWIATOWA_DOBRY_DOM,

    // TODO KOBIETKI


    ME, YOU, ALL, SRODOWISKO,
}
