package typy_bazowe;

/**
 * Created by gadzik on 31.12.19.
 */
public enum TypT {
    // PREFIX
    UBRANIE_WYGLAD_SZCZEGOLY, CEL, PLANY_DZIS, DAILY_WORRIES, OTOCZENIE, POGODA,

    // PRZEDSTAWIENIE SIE
    IMIE, MIESZKA, KONTEKST,

    // UTRZYMYWACZE
    PRZEWIDZENIE, WNIOSKI, DEEP, KONTRA, COMPARE, ZART, POTWIERDZENIE, JAKI_JAKA_JAKIE,

    //    nadTematy
    WYGLAD, CZAS_MIEJSCE, EMOCJE_UCZUCIA, OSOBY_POWIAZANE, ZMYSLY, DOSWIADCZENIE, OSTATNIO_WIDZIANE, COS_NOWEGO, PRZED_PO,
    OCZEKIWANIA_RZECZYWISTOSC, POWSZECHNOSC, PLUSY_MINUSY, KROKI, CENA,

    // HIERARCHIA
    WAZNE_NAJBLIZSZA_PRZYSZLOSC, WAZNE_DLUGA_PERSPEKTYWA, WAZNE_OSTATNIA_PRZESZLOSC, WAZNE_PRZESZLOSC_WPLYW_TERAZNIEJSZOSC,
    DOTYCZY_WAZNYCH_OSOB, PRZEWAGA, DOMINACJA, DOBRA, HIERARCHIA, ZASADY, DOSTEP,

    /*WYGLAD,*/


    RZECZ,
    POTRZEBA, KOLOR, TYP, ATRYBUTY, POROWNANIE, /*CENA,*/ UZYTECZNOSC, WYTRZYMALOSC, OSTATNIO_WIDZIANY,  POPULARNOSC,
    PROCES_POZYSKANIA, ZAKUPY,

    MIEJSCE,
    WYSTROJ, KOLEJKA,TLOK, /*POPULARNOSC,*/ DOJAZD, ZALETY, WADY, OKOLICA,

    ZYWE_ISTOTY,
    CECHY_CHARAKTERU, PLEC, CECHY_FIZYCZNE, GENY, NAUKA, PRZYWIAZANIE, UCZUCIA, UMIEJETNOSCI,

    SPEDZANIE_CZASU,
    DZIALANIA, /*DAILY_WORRIES,*/ PRACA, TRENING, PASJA,


    RELACJE,
    ZACHOWANIA, REAKCJE, GENEZA_ZNAJOMOSCI,

    RODZINA,
    DOM, DZIECI, RODZIENSTWO, RODZICE, DZIADKOWIE,

    MORALNOSC_PRZEKONANIA_RELIGIA,

    ZDROWIE,
    CODZIENNY_MAINTENCE, LEKARSTWA, SPA,

    MIASTA,
    BLISKOSC, KLIMAT, KOMUNIKACJA, LUDZIE,

    MARZENIA,

    MOMENT_W_HISTORII, CYKL_W_ZYCIU,

    SPORT,
    DYSCYPLINY, TRENERZY, ZDOLNI_SPORTOWCY, HISTORIA_TRENINGOW,

    GOTOWANIE,
    PRZEPIS, SMAK, RESTAURACJE,

    HOLIDAYS,
    BASENY_WODA, PL_ZA, BEZPIECZENSTWO, ODLEGLOSC, SPECYFICZNY_KRAJOBRAZ,

    SWIETA,


}
