package typy_bazowe;

/**
 * Created by gadzik on 22.12.19.
 */
public enum TypZadania {
    JEDZENIE, SZYKOWANIE,
    PRACA, NAUKA, TRENING, TRENING_BOKS, TRENING_SILOWY_DOM, SILKA, BIEGANIE,
    ZNAJOMI, ZAKUPY, MELANZ,

    GOTOWANIE, PRANIE, PRASOWANIE, SPRZATANIE,
    POZNAWANIE, KLUBY
}
