package miejsce;

/**
 * Created by gadzik on 29.12.19.
 */
public enum HotSpot {
    PRZYSTANEK, TRAUTO,
    SKLEP, RESTAURACJA,
    PARKING, STACJA_BENZYNOWA, POCZTA, BANK,
    KOLEJKA, UJSCIE, SCHODY, SWIATLA, PRZECIECIE_SCIEZEK, PIESEK,
    OSIEDLE_MSC_SRODOWISKOWE
}
