package metoda;

/**
 * Created by gadzik on 29.12.19.
 */
public enum HotTopic {
    POWIAZANE_Z_WYGLADEM_UBIOREM, WYWOLUJACE_EMOCJE, WYNIK, PRZEWIDYWANIE, POWIAZANE_Z_HOBBY, INTERESUJACE, POWIAZANE_Z_OSOBAMI,
    // todo
    GLEBOKIE, SENTYMENTALNE, HISTORIE,
}
