/**
 * Created by gadzik on 22.12.19.
 */
public class Consts {

    public enum WarunkiWstepne {
 // INFORMACJA
        CZAS, DOSTEP_DO_PLANSZY, LUDZIE, MATERIALNE_ZNALEZIENIE_SIE, SONDA, SZCZEGOLY,

 // WIEDZA
        INFORMACJA, PRZYCZYNA, SKUTEK, WNIOSKI,

 // BRAKWSTYDU
        /* INFORMACJA,*/  WIEDZA, DZIALANIE,

 // REZULTAT
        /* DZIALANIE,*/ KONSEKWENCJE, /*WNIOSKI,*/ REZULTAT,

 // SWIAT
        ZWIAZEK_2_OSOB, URODZENIE_SIE, ZDROWIE, BYT_MATERIALNY,

 // PRACA
        NIEKARALNOSC, WYKSZTALCENIE, DOSWIADCZENIE, UMIEJETNOSCI, ZNAJOMOSCI,

 // PRACA RESTRYKCYJNA
        /*NIEKARALNOSC,*/ STUDIA, KILKA_LAT_DOSWIADCZENIA, WIELE_UMIEJETNOSCI, Z_POLECENIA,

 // ZARABIANIE
        UMOWA_PRACA, WYKONYWANIE_PRACY,

 // SPORT
        /*CZAS,*/ SPRAWNOSC, ZDOLNOSC_DO_WYSILKU, EKWIPUNEK, ZGODA_OTOCZENIA,

 // OSIEDLE
        TO_SAMO_MIASTO, DOBRZE_WYGLADA, ZNAJOMY_W_SRODOWISKU,
        NIE_PRZECIWNY, NIE_KONFI,

 // DOPUSZCZENIE
        PATRZY, REAGUJE, USMIECHA, DOBRO,
        KOJARZY, KTORYS_RAZ, WSPOLNI_ZNAJOMI,
        BEZPIECZENSTWO, NUDA, PODOBA_SIE,
        MUSI_DOPUSCIC,

 // KOBIETA
        PODBICIE, POZNANIE,
        DOPUSZCZENIE,
        PARZONKO_XKILKA, SPODOBANIE_SIE,
        PLUS_GT_MINUS
    }

    public enum WarunkiUtrzymania {
 // INFORMACJA
        CZAS, DOSTEP_DO_PLANSZY, LUDZIE, MATERIALNE_ZNALEZIENIE_SIE, SONDA, SZCZEGOLY, CHECK,

 // WIEDZA
        ODSWIEZANIE, PAMIEC, ULEPSZANIE,

 // BRAKWSTYDU
        LEPSZE_WYKORZYSTANIE_INFORMACJI, LEPSZE_DZIALANIE, WNIOSKI,

 // REZULTAT
        /* LEPSZE_DZIALANIE,*/ UNIKNIECIE_KONSEKWENCJI, PRZEWIDYWANIE, REZULTAT, UTRZYMANIE,

 // SWIAT
        ZNAJOMI, SWOJ_ZWIAZEK, UNIKANIE_ZAGROZEN, DBANIE_ZDROWIE, ZARABIANIE,

 // PRACA
        PRZESTRZEGANIE_ZASAD, ATMOSFERA, WYSILEK, UZYTECZNOSC, REZULTATY, OPLACA, STOSUNEK1VS1, ULEPSZANIE_UMIEJETNOSCI, PLUS_GT_MINUS,

 // ZARABIANIE
        BOGATY_SEKTOR, WIEDZA, NISZA, REGION,

 // PRACA RESTRYKCYJNA
        /*NIEKARALNOSC,*/ STUDIA, KILKA_LAT_DOSWIADCZENIA, WIELE_UMIEJETNOSCI, Z_POLECENIA,

 // SPORT
        /*CZAS,*/ SPRAWNOSC, ZDOLNOSC_DO_WYSILKU, EKWIPUNEK, ZGODA_OTOCZENIA,

 // OSIEDLE
        TO_SAMO_MIASTO, DOBRZE_WYGLADA, ZNAJOMY_W_SRODOWISKU,
        NIE_PRZECIWNY, NIE_KONFI,

 // DOPUSZCZENIE
        PATRZY, REAGUJE, USMIECHA, DOBRO,
        KOJARZY, KTORYS_RAZ, WSPOLNI_ZNAJOMI,
        BEZPIECZENSTWO, NUDA, PODOBA_SIE,
        MUSI_DOPUSCIC,

 // KOBIETA
        PODBICIE, POZNANIE,
        DOPUSZCZENIE,
        PARZONKO_XKILKA, SPODOBANIE_SIE,
        /*PLUS_GT_MINUS*/
    }

    public enum WWInformacja {
        CZAS, DOSTEP_DO_PLANSZY, LUDZIE, MATERIALNE_ZNALEZIENIE_SIE, SONDA, SZCZEGOLY
    }

    public enum WWWiedza {
        INFORMACJA, PRZYCZYNA, SKUTEK, WNIOSKI
    }

    public enum WWBrakWstydu {
        INFORMACJA, WIEDZA, DZIALANIE
    }

    public enum WWRezultat {
        DZIALANIE, KONSEKWENCJE, WNIOSKI, REZULTAT
    }


    public enum WWSwiat {
        ZWIAZEK_2_OSOB, URODZENIE_SIE, ZDROWIE, BYT_MATERIALNY
    }

    public enum WWPraca {
        NIEKARALNOSC, WYKSZTALCENIE, DOSWIADCZENIE, UMIEJETNOSCI, ZNAJOMOSCI
    }

    public enum WWPracaRestrykcyjna {
        NIEKARALNOSC, STUDIA, KILKA_LAT_DOSWIADCZENIA, WIELE_UMIEJETNOSCI, Z_POLECENIA
    }

    public enum WWSport {
        CZAS, SPRAWNOSC, ZDOLNOSC_DO_WYSILKU, EKWIPUNEK, ZGODA_OTOCZENIA
    }

    public enum WWOsiedle {
        TO_SAMO_MIASTO, DOBRZE_WYGLADA, ZNAJOMY_W_SRODOWISKU,
        NIE_PRZECIWNY, NIE_KONFI
    }

    public enum WWDopuszczenie {
        PATRZY, REAGUJE, USMIECHA, DOBRO,
        KOJARZY, KTORYS_RAZ, WSPOLNI_ZNAJOMI,
        BEZPIECZENSTWO, NUDA, PODOBA_SIE,
        MUSI_DOPUSCIC
    }

    public enum WWKobieta {
        PODBICIE, POZNANIE,
        DOPUSZCZENIE,
        PARZONKO_XKILKA, SPODOBANIE_SIE,
        PLUS_GT_MINUS
    }

    public enum WUKobieta {
        PLUS_GT_MINUS, ZGODA_OTOCZENIA,
        SPEDZANIE_CZASU
    }
    public enum WKoncowe {
        SZCZESCIE, DOSWIADCZENIA, WSPOMNIENIA,
        ZNAJOMI,
        DZIECI,
        HAJS,
        SPRAWNOSC, SILA
    }

    public enum Zasady {

    }

    public enum Zagrozenia {

    }

    public enum HotSpot {
        KOLEJKA, UJSCIE, SCHODY,
        PARKING, SKLEP, PRZYSTANEK, TRAUTO, OSIEDLE_MSC_SRODOWISKOWE
    }

    public enum WarunkiS {

    }

    public enum WarunkiNS {

    }

    public enum Potrzeba {

    }

    public enum Przymus {

    }

    public enum PrzyczynyZla {
        GENY, GLUPOTA, NARKOTYKI
    }

    public enum Wartosc {
        WYGODY, ROZRYWKI, PIENIADZE, SRODOWISKO, ZASADY,  UMIEJETNOSCI;
    }

}
