/**
 * Created by gadzik on 21.12.19.
 */
public enum Metoda {
 // PODBITKA
    SMIETNIIK_NA_BUZI_JUZ_DAWNO,
    NAMIERZENIE,
    SONDA_OSOBY, SONDA_SYTUACJI,


    REMIND /*TODO */, ANTY_PARTYZANTKA,

    SPOJRZENIE, PRZEJSCIE, ZAGADANIE, ZWROCENIE_UWAGI,


 // GADKA

 // POZNANIE

 // NIUNI


// DZIALANIE SPRZET

 // OSIEDLOWEGO

 // CZORTA

 // MANAGERA

 // WYCHOWYWANIE

   // NEGOCJACJE TODO: NEGOCJACJE JAKO WARUNEK, WARUNKI UTRZYMANIA, przenies do metod
   PROSBA,
   PRZEKONYWANIE_SENTYMENTEM, PRZEKONYWANIE_ARGUMENTAMI , PRZEKONYWANIE_WARTOSCIA, PRZEKONYWANIE_OTOCZENIA,
   SZANTAZ, STARCIE


   ;
    public static void methods(){}

}
