/**
 * Created by gadzik on 26.12.19.
 */
public enum TypKategoria {
    GLOBAL_PLANSZA,
    LUDZIE, /*PRACA,*/ MIEJSCA,

    WYMAGANIA_WSTEPNE, WYMAGANIA_UTRZYMANIA, WARUNKI_KONCOWE,

    SWIAT, INFORMACJA, WIEDZA, BRAKWSTYDU, REZULTAT, PRACA, PRACA_RESTRYKCYJNA, ZARABIANIE, SPORT, OSIEDLE, DOPUSZCZENIE, KOBIETA,

    ZASADY, ZAGROZENIA, HOTSPOT, HOTTOPIC, POTRZEBA, PRZYMUS,

    PRZYCZYNY_ZLA,

    WARTOSC, OCENIA_WEDLUG,

    THREAD_WHILE_LOOP,

    PRZEWAGI
}
