/**
 * Created by gadzik on 20.12.19.
 */
public enum TypOsoby {
    LOKALNY, TURYSTA_ZAGRANICZNY, STATYSTA,
    STARY, SREDNI_WIEK, MLODY,

    FEST, BANAN, SYSTEMOWY_BURZUJ, WYGODNIS,
    OSIEDLOWY_BURZUJ, OSIEDLOWY_WYKRECONY, OSIEDLOWY_CASUAL, SPORTOWY_FEST,
    OSIEDLOWY_NORMAL, OSIEDLOWY_OGARNIETY,
    BIEGACZ, PATOLOG, DIL, ZLODZIEJ,

    CZORT, OSIEDLOWA_KARYNA, OSIEDLOWA_KSIEZNICZKA, OSIEDLOWA_AGRESORKA, OSIEDLOWA_NORMALNA, OSIEDLOWA_DOBRA,
}
