/**
 * Created by gadzik on 20.12.19.
 */
public enum TypOsoby {
    FEST, SYSTEMOWY_BURZUJ, WYGODNIS, OSIEDLOWY_BURZUJ, OSIEDLOWY, SPORTOWY_FEST, BIEGACZ, PATOLOG, DIL, ZLODZIEJ,
    LOKALNY, TURYSTA_ZAGRANICZNY,
}
