package warunek;

/**
 * Created by gadzik on 22.12.19.
 */
public enum W {
        // *** *** *** *** *** *** *** *** *** WSTEPNE *** *** *** *** *** *** *** ***

        // SWIAT
        ZWIAZEK_2_OSOB, URODZENIE_SIE, ZDROWIE, BYT_MATERIALNY,

        // INFORMACJA
        CZAS, DOSTEP_DO_PLANSZY, LUDZIE, MATERIALNE_ZNALEZIENIE_SIE, SONDA, SZCZEGOLY,

        // WIEDZA
        INFORMACJA, PRZYCZYNA, SKUTEK, WNIOSKI,

        // BRAK_WSTYDU
        /* INFORMACJA,*/  WIEDZA, DZIALANIE,

        // REZULTAT
        /* DZIALANIE,*/ KONSEKWENCJE, /*WNIOSKI,*/ REZULTAT,

        // PRACA
        NIEKARALNOSC, WYKSZTALCENIE, DOSWIADCZENIE, UMIEJETNOSCI, ZNAJOMOSCI,

        // PRACA RESTRYKCYJNA
        /*NIEKARALNOSC,*/ STUDIA, KILKA_LAT_DOSWIADCZENIA, WIELE_UMIEJETNOSCI, Z_POLECENIA,

        // ZARABIANIE
        UMOWA_PRACA, WYKONYWANIE_PRACY,

        // SPORT
        /*CZAS,*/ SPRAWNOSC, ZDOLNOSC_DO_WYSILKU, EKWIPUNEK, ZGODA_OTOCZENIA,

        // OSIEDLE
        TO_SAMO_MIASTO, DOBRZE_WYGLADA, ZNAJOMY_W_SRODOWISKU,
        NIE_PRZECIWNY, NIE_KONFI,

        // DOPUSZCZENIE
        PATRZY, REAGUJE, USMIECHA, DOBRO,
        KOJARZY, KTORYS_RAZ, WSPOLNI_ZNAJOMI,
        BEZPIECZENSTWO, NUDA, PODOBA_SIE,
        MUSI_DOPUSCIC,

        // KOBIETA
        STWORZENIE_POINTCUTA,
        ZLAPANIE_POINTCUTA,
        POZNANIE,
        DOPUSZCZENIE,
        PARZONKO_XKILKA, SPODOBANIE_SIE,
        PLUS_GT_MINUS, WOLNA,

        // *** *** *** *** *** *** *** *** *** WSTEPNE *** *** *** *** *** *** *** ***

        // *** *** *** *** *** *** *** *** *** UTRZYMANIA *** *** *** *** *** *** *** ***

        // SWIAT
        ZNAJOMI, SWOJ_ZWIAZEK, UNIKANIE_ZAGROZEN, DBANIE_ZDROWIE, ZARABIANIE,

        // INFORMACJA
        SLEDZENIE_INFORMACJI, REZULTAT_INFORMACJI, POTWIERDZENIE_Z_KIMS, SPRAWDZENIE_SAMEMU,

        // WIEDZA
        ODSWIEZANIE, PAMIEC, ULEPSZANIE, DZIELENIE_SIE_WIEDZA,

        // BRAK_WSTYDU
        LEPSZE_WYKORZYSTANIE_INFORMACJI, LEPSZE_DZIALANIE, /*WNIOSKI,*/

        // REZULTAT
        /* LEPSZE_DZIALANIE,*/ UNIKNIECIE_KONSEKWENCJI, PRZEWIDYWANIE, /*REZULTAT,*/ UTRZYMANIE,


        // PRACA
        /*WYSILEK, UZYTECZNOSC, OPLACA, PLUS_GT_MINUS,*/

        // ZARABIANIE
        BOGATY_SEKTOR, /*WIEDZA,*/ NISZA, REGION,

        // PRACA RESTRYKCYJNA
        PRZESTRZEGANIE_ZASAD, ATMOSFERA, WYSILEK, UZYTECZNOSC, REZULTATY, OPLACA, STOSUNEK1VS1, ULEPSZANIE_UMIEJETNOSCI, /*PLUS_GT_MINUS,*/

        // SPORT
        /*CZAS, SPRAWNOSC, ZDOLNOSC_DO_WYSILKU, EKWIPUNEK, ZGODA_OTOCZENIA,*/

        // OSIEDLE
        CZESTO_Z_CELEM, /*DZIALANIE,*/ ZACIESNIENIE_GRONA_ZNAJOMYCH,
        STO_PRO_LOJALNY, /*PRZESTRZEGANIE_ZASAD,*/

        // DOPUSZCZENIE
        DOBRZE_ZNA, /*WSPOLNI_ZNAJOMI,*/
        /*BEZPIECZENSTWO,*/ EMOCJE, /*PODOBA_SIE,*/
        /*PLUS_GT_MINUS,*/

        // KOBIETA
        /*PLUS_GT_MINUS, ZGODA_OTOCZENIA,*/
        SPELNIENIE_OCZEKIWAN,
        WSPIERANIE_PREFERENCJI,
        ODKRYWANIE_SWIATA,
        SPEDZANIE_CZASU,
        WIERNOSC,

        PILNOWANIE, KONTROLA,

        // *** *** *** *** *** *** *** *** *** UTRZYMANIA *** *** *** *** *** *** *** ***

        // KONCOWE
        SZCZESCIE, DOSWIADCZENIA, WSPOMNIENIA,
        /*ZNAJOMI,*/
        KOBIETA, DZIECI,
        /*PIENIADZE, BEZPIECZENSTWO,*/ STABILIZACJA, POZOSTANIE_W_KRAJU, /*ULEPSZANIE_UMIEJETNOSCI,*/
        MOZLIWOSC_WYBORU,
        /*SPRAWNOSC,*/ SILA, ZMUSZASZ,
        SILNE_JEDNOSTKI, OSZCZEDNOSC_CZASU, AKCEPTACJA, LATWY_DOSTEP_PRZEWAGI,
        CODZIENNA_BLISKOSC, ZYCIE_RAZEM,

        // PRZYCZYNY ZLA
        ZLE_GENY, GLUPOTA, NARKOTYKI, NIESWIADOMOSC, DZIALANIE_ZA_NAMOWA,

        // WARTOSC
        WYGODY, ROZRYWKI, PIENIADZE, SRODOWISKO, ZASADY, /*UMIEJETNOSCI,*/ IDEA, NAUKA, SPORT, WSPIERANIE_SWOJEJ_KLASY,
        MODA, BECZKA, KOLEZANKI, WRAZLIWOSC, /*DZIECI,*/ CHLOP, RODZINA,

        // GLOBAL PLANSZA
        /*LUDZIE,*/
        DZIETNOSC, WYCHOWANIE, MIESZKANIE,

        PRACA,
        FIRMY_NIEWYMAGAJACE_DOSWIADCZENIE, FIRMY_WYMAGAJACE_DOSWIADCZENIE, RYNEK_PLAC, ZASOBY_LUDZKIE,

        MIEJSCA,

        // OCENIA WG
        ZLO, /*DOBRO,*/ ZYSK, EKIPA, PRZEWAGA, UMIEJETNOSC, PODOBIENSTWO, WARUNEK_SPRZYJAJACY,

        // THREAD WHILE LOOPS
        THREAD_WHILE_LOOP_BLISKOSC_K, THREAD_WHILE_LOOP_ZASIEG_WZROKU,
        THREAD_WHILE_LOOP_EFEKTYWNA_GADKA,

        THREAD_WHILE_LOOP_BLISKOSC_U,

        // PRZEWAGI
        /*ZNAJOMI,*/ OSIEDLOWE_SRD, /*KOBIETA,*/
        SZANSA_ZNAJOMI, SZANSA_OSIEDLOWE_SRD, SZANSA_KOBIETA,
        /*INFORMACJA, CZAS, WIEDZA,*/ BRAK_WSTYDU,
        LUDZIE_ZA_TOBA, WALKA_PIESCI, WALKA_SPRZET,
        /*UMIEJETNOSC,*/
        /*PRACA, PIENIADZE,*/
        WYSOKA_POZYCJA,
        SPRYT, SZYBKOSC, PRZEZYCIE_CIERPIENIA, SILNY, POTRAFI_OCENIC,
        // CHARAKTERU
        TEN_SAM_KOLOR_SKORY, TA_SAMA_RASA, TA_SAMA_NARODOWOSC, PLEC_MEZCZYZNA, CIEZKIE_WYCHOWANIE, POZNANIE_CIERPIENIA, DOBRY_PRIORYTET,
        OCENIAWG_DOBRO, OCENIAWG_PODOBIENSTW, OCENIAWG_PRZEWAG, OCENIAWG_UMIEJETNOSC,
        DUZO_PRZEWAG, DUZO_PRZEZYC, DUZO_ODWIEDZONYCH_PLANSZ, DUZO_METOD, BRAK_BURZUAZJI, DOBRA_PAMIEC, PRIORYTETOWE_SRODOWISKO_DZIELNICA, DUZO_UMIEJETNOSCI,
        /*DOBRO,*/ REAGUJE_NA_DOBRO, Z_MIASTA, WYSILEK_FIZYCZNY, WYSILEK_UMYSLOWY, MOCNY_WZROK, DOBRY_GEN,
        SWIADOMOSC, SWIADOMOSC_ULICY, SWIADOMOSC_ZAGROZEN, SWIADOMOSC_PRZEWAG, SWIADOMOSC_RYNKU_PRACY, SWIADOMOSC_PATOLOGII_ZWIAZKOW,
        /*WIEDZA, SILNY,*/ POSIADA_CELE, Z_KIMS, Z_MOCNYM, CZYNNY, STWARZA_POINTCUTY, CHCE_LEPSZEGO_ZYCIA, TEPI_KURESTWO, MA_ZASADY,
        ZWAZA_NA_MIEJSCE, ZWAZA_NA_OKOLICZNOSC, ZWAZA_NA_OSOBY, ZWAZA_NA_WYSILEK, ZWAZA_ILE_KTO_PRACOWAL, OLEWA_PRZEWAGI_PRZY_OCENIE,
        KREGOSLUP_MORALNY, THREAD_WHILE_LOOP_U, DOSTEP_DOBRE_JEDNOSTKI, DOSTEP_BIEGACZE, MAGICZNE_ZAKLECIA, WIE_OD_KOGO_JEST,
        KONFRONTACJA_F2F, ZDOLNY_DO_WALKI, ZDOLNY_WALKA_SPRZET, ZDOLNY_DO_RYZYKA, STWARZA_ZAGROZENIE, SMIALY, BEZPOSREDNI, UMIE_KLUCIC, UMIE_CISNAC, BRONI_GLOBALU,
        UDZIELA_DOSTEPU, DZIELI_SIE_DOBRAMI, ZDOLNY_DO_WYBACZENIA, STALE_POGLADY, NIEZALEZNY, /*MADROSC,*/ OSTROZNIE_OCENIA, ZWAZA_NA_KAZDA_INFORMACJE,
        WSPIERA_W_OSIAGNIECIU_PRZEWAGI, /*CIERPLIWOSC, PRAWDA,*/ DOBRA_SONDA, CHETNY_DZIALANIA, BIEDNY, MA_RODZENSTWO, ANTY_SYSTEM, BRAK_STUDIOW,
        /*NIEBEZPIECZENSTWO,*/ ZWAZA_NA_ZAGROZENIE, ZNA_CIERPIENIE, OSTROZNY, PRAWDZIWY, ZYJE_DLUGOTERMINOWO, TRAKTUJE_POWAZNIE,
        TWARDY, NARODOWY, RASISTA, MA_CZAS, DOSTEPNY, MA_PRACE, TRZEZWY,
        LADNY, DZIEWICA, MILY, OTWARTY_NA_ZWIAZEK, DOPUSZCZA_NIEZNAJOMYCH, USMIECHA_SIE, SMIEJE_SIE, /*PATRZY,*/ REAGUJE_NA_BODZCE,
        MALA_ILOSC_PARTNEROW, /*DZIECI,*/
        MA_STANDARD_ZACHOWANIA, DUZO_ZNAJOMYCH, DUZO_DOBRYCH_ZNAJOMYCH, SZANSA_NA_MADROSC, SZANSA_NA_RELIGIE,

        // SLABOSCI
        /*BRAK_ZNAJOMYCH, BRAK_SRODOWISKA, BRAK_KOBIETY,*/
        BRAK_SZANS_ZNAJOMI, BRAK_SZANS_SRODOWISKO, BRAK_SZANS_KOBIETA,
        /*BRAK_INFORMACJI, BRAK_CZASU, BRAK_WIEDZY,*/ WSTYD,
        BRAK_LUDZI_ZA_TOBA, NIEZDOLNY_WALKA_PIESCI, NIEZDOLNY_WALKA_SPRZET,
        /*BRAK_UMIEJETNOSCI,
        BRAK_PRACY, BRAK_PIENIEDZY,*/
        SLABA_POZYCJA,
        TEMPOTA, POWOLNY, PRZEZYCIE_WYGOD, PRZEZYCIE_DOBRA, SLABY, NIEUMIE_OCENIC,
        // CHARAKTERU
        INNY_KOLOR_SKORY, INNA_RASA, INNA_NARODOWOSC, PLEC_KOBIETA, BURZUAZYJNE_WYCHOWANIE, NIEZAZNANIE_CIERPIENIA,
        BLEDNY_PRIORYTET, OCENIAWG_ZLO, OCENIAWG_ZYSK, OCENIAWG_EKIPA,
        MALO_PRZEWAG, MALO_PRZEZYC, MALO_ODWIEDZONYCH_PLANSZ, MALO_METOD, DUZO_BURZUAZJI, SLABA_PAMIEC,
        PRIORYTETOWE_SRODOWISKO_RODZINA, MALO_UMIEJETNOSCI,
        ARCY_ZLO, DZIALA_DLA_DIABLA, /*ZLO,*/ REAGUJE_NA_ZLO, ZE_WSI, BRAK_WYSILKU_FIZYCZNEGO, BRAK_WYSILKU_UMYSLOWEGO,
        SLABY_WZROK, SLABY_GEN, /*NIESWIADOMOSC,*/
        NIESWIADOMOSC_ZAGROZEN, NIESWIADOMOSC_ULICY, NIESWIADOMOSC_PRZEWAG, NIESWIADOMOSC_RYNKU_PRACY, NIESWIADOMOSC_PATOLOGII_ZWIAZKOW,
        /*BRAK_WIEDZY, SLABY, BRAK_CELU,*/ SAM, Z_NIEWAZNYM, BIERNY, NIESTWARZA_POINTCUTOW, CHCE_WYGOD, KURESTWO, BRAK_ZASAD,
        PIERDOLI_GO_MIEJSCE, PIERDOLI_GO_OKOLICZNOSC, PIERDOLA_GO_OSOBY, PIERDOLI_GO_TWOJ_WYSILEK, PIERDOLI_GO_ILE_PRACOWALES, WYKORZYSTUJE_BRAK_PRZEWAG,
        BRAK_KREGOSLUPA_MORALNEGO, BRAK_THREAD_WHILE_LOOP_U, BRAK_DOSTEPU_DOBRE_JEDNOSTKI, BRAK_DOSTEPU_BIEGACZE, BRAK_MAGICZNYCH_ZAKLEC, BRAK_OD_KOGO_JESTES,
        PO_CICHU, NIEZDOLNY_WALKA, NIEZDOLNY_RYZYKO, NIESTWARZA_ZAGROZENIA, /*WSTYD,*/ NIEUMIE_KLUCIC, NIEUMIE_CISNAC, BRONI_HIERARCHII,
        WYKLUCZA, UKRYWA_DOBRA, SKRESLA_NA_ZAWSZE, STALE_DOKRECA_SRUBE, RESETABLE,
        POSLUSZNY, PRZEKONYWALNY, ZALEZNY,
        GLUPI, TRAKTOWANIE_Z_GORY, IGNOROWANIE_INFORMACJI,
        LUKI_OSOBOWOSCI, EGOISTA, /*ZAZDROSC,*/ AGRESJA, /*KLAMSTWO,*/ NIESTABILNOSC_UMYSLOWA, BRAK_OKRESLENIA_SKALI, BRAK_CHECI_DZIALNIA,
        HAJS_W_DOMU, BOGATY, JEDYNAK, SYSTEMOWIEC, /*STUDIA,*/
        /*BEZPIECZENSTWO,*/ BAGATELIZUJE_ZAGROZENIE, NIEZNA_CIERPIENIA, ZUCHWALY, SZTUCZNY,
        ZYJE_Z_DNIA_NA_DZIEN, WYJEBANE,
        WRAZLIWY, WOLNOSC_LEKKOSC, EUROPEJSKI, /*BRAK_CZASU,*/ NIEDOSTEPNY,
        NALOG, /*NARKOTYKI,*/ PALENIE, /*PICIE,*/
        BRZYDKI, BRAK_SEXU, SEX, SEX_Z_PARTNEREM, SEX_ZE_ZNAJOMIMI, SEX_Z_NIEZNAJOMYMI, SEX_Z_ZAGRANICZNYMI, SEX_MIEDZY_RASOWY,
        WYJEZDZENIE, SZLAUF, WOREK_NA_SPERME_ZAGRANICZNYCH,
        NIEMILY, ZAMKNIETY_NA_ZWIAZEK, RESTRYKCJA_ZNAJOMYCH,
        ODWRACA_WZROK, NIEREAGUJE_NA_BODZCE,
        ZAJETY, DUZA_ILOSC_PARTNEROW, /*BRAK_DZIECI,*/ PRZESTRZEGA_PRAWA,
        WYROK, PRZEJEBANE, HANBA,
        /*KONFI,*/
        MALO_ZNAJOMYCH, MALO_DOBRYCH_ZNAJOMYCH,

        // CIERPIENIE
        ZMECZENIE, CIERPIENIE_FIZYCZNE, CIERPIENIE_PSYCHICZNE, CIERPIENIE_PRZEMIJANIA, CIERPIENIE_UTRATY,
        CIERPIENIE_SAMOTNOSCI, CIERPIENIE_WIDZENIE_BRAK_DOTKNIECIA,
        ZMECZENIE_DLUGOTRWALE, CIERPIENIE_FIZYCZNE_DLUGOTRWALE, CIERPIENIE_PSYCHICZNE_DLUGOTRWALE,
        CIERPIENIE_PRZEMIJANIA_DLUGOTRWALE, CIERPIENIE_UTRATY_DLUGOTRWALE, CIERPIENIE_SAMOTNOSCI_DLUGOTRWALE,
        CIERPIENIE_WIDZENIE_BRAK_DOTKNIECIA_DLUGOTRWALE,


        // ZAGROZENIA
        STRATA_WOLNOSCI, STRATA_CZASU, STRATA_INFORMACJI, STRATA_WIEDZY,
        STRATA_DOSTEPU_PLANSZA, STRATA_DOSTEPU_ZNAJOMI, STRATA_MIEJSCA_W_HIERARCHII, STRATA_POZYCJI,
        STRATA_ZDROWIA, STRATA_HONORU,
        STRATA_PRACY, STRATA_PIENIEDZY, STRATA_ZARABIANIA, STRATA_WYKSZTALCENIA,
        STRATA_KOBIETY, ROZWOD, ALIMENTY,

        // ZASADY
        PRAWO, /*NIE_KONFI,*/ NIE_PRZECIWNA, NIEZNAJOMY_JEBAC,
        NIEGADAJ_Z_OBCYMI, NIEGADAJ_Z_POZAOSIEDLA, NIEGADAJ_Z_NIESLAZAKAMI,
        KTO_NIEBIEGA_TUBA,
        JEDNOSC_PRZECIW_ZAZDROSCI,
        R1_HOLD_YOUR_POSITION, R2_ONLY_ONE_CHANCE_TO_SCORE, R3_LIFE_IN_YOUR_HANDS_NOT_LORDS,
        R4_WATCH_YOUR_ACTIONS,

        // POTRZEBA
        KONTAKTU, AKCEPTACJI, DOBRYCH_JEDNOSTKEK, ZWIAZKU, ZROZUMIENIA, HIGIENY, UBRANIA, RELIGII, /*ROZRYWKI,*/ RUCHU,
        // PRZYMUS
        JEDZENIE, PICIE, /*PRACA,*/ EDUKACJA, PRZEMIESZCZANIE_SIE, TRANSPORT, KUPNO_PRODUKTOW, PRZEMIESZCZENIE_SIE,
        // NIESPRAWIEDLIWOSC
        PRACA_XCZASU_BRAK_REZULATU, WDUPCANIE_WYSILKU_DO_PIECA, NADUZYWANIE_WYSOKIEJ_POZYCJI, GORZEJ_NA_STARCIE, PRZEWAGA_NA_STARCIE,
        STRONNICZOSC, WYKLUCZENIE,


        // DOBRY
        ROBIENIE_PROGRESU, ZDOBYWANIE_UMIEJETNOSCI, ZDOBYWANIE_WIEDZY, ZDOBYWANIE_SILY, USWIADAMIANIE,
        WYCIAGANIE_ZE_ZLEJ_SYTUACJI, ZMNIEJSZANIE_ZLA, ROBIENIE_OPCJI, PRZEKONYWANIE_ZA, POLECENIE,
        PRAWDA, CIERPLIWOSC,
        TRZEZWOSC,
        MADROSC,
        NOWY_DEFAULT_DOBRA_OSOBA,
        NIEPOZWALA_NA_ZLO,
        TWORZENIE_KONTAKTU, TWORZENIE_ISTNIENIA,

        // ZLY
        MARNOWANIE_CZASU, POZBAWIANIE_UMIEJETNOSCI, POZBAWIANIE_WIEDZY, POZBAWIANIE_SILY, OGLUPIANIE,
        WDUPCANIE_W_ZLE_WARUNKI, ZAMYKANIE_OPCJI, PRZEKONYWANIE_PRZECIW,
        KLAMSTWO, AGRESJA_FIZYCZNA, AGRESJA_PSYCHICZNA,
        ODUZENIE,
        /*GLUPOTA,*/
        NOWY_DEFAULT_RYWAL,
        JEBIE_DOBRO, WYMAGA_PRZEWAG_NA_ZLU,
        SKAZYWANIE_SAMOTNOSC, SKAZYWANIE_PUSTKA,

        // WYMUSZENIE REAKCJI
        KONTEKST, OSKARZENIE, ULTIMATUM, CISNIECIE,

        // REAKCJA
        BRAK_ODPOWIEDZI, PRZESTRASZENIE_SIE, UCIECIE,
        ODPOWIEDZ_ODCZEP, ODPOWIEDZ_NEUTRAL, ODPOWIEDZ_ZAINTERESOWANIE,
        EKSCYTACJA, PRZEJCIE_INICJATYWY,

        // SONDA GDY
        WIDZISZ, MOWI, ROBI, POSIADA,

        // SONDA PO
        OCZY, REAGOWANIE, CHODZENIE, POSTURA, ZACHOWANIE, MOWA, /*ZNAJOMI,*/

        // KRYTERIA WROGA
        PRZECIWNA_RASA, PRZECIWNY_NAROD, PRZECIWNA_KLASA, PRZECIWNY_KLUB, PRZECIWNA_STRONA, ZASZKODZIL,

        // CYKL DNIA
        OD_00_DO_6, OD_6_DO_7, OD_7_DO_9, OD_9_DO_11_, OD_11_DO_14,
        OD_14_DO_17, OD_17_DO_19, OD_19_DO_21, OD_21_DO_24,
        PRZED_9, PO_17,

        // PLAN
        CYKL_DNIA, DZIEN, TYDZIEN, MIESIAC, TRZY_MIESIACE, POL_ROKU, ROK,

        // ZART
        UKAZANIE_OSOBY_W_KOMICZNEJ_SYTUACJI, WYOLBRZYMIENIE, ZAMIANA, RZECZYWISTOSC_ODBIEGAJACA_OD_NORMY,

        // ERA
        PONIZEJ_1900, OD_1900_DO_1939, OD_1939_DO_1945, OD_1945_DO_1953, OD_1953_DO_1970,
        OD_1970_DO_1990, OD_1990_DO_2000, OD_2000_DO_2005, OD_2005_DO_2011, OD_2011_DO_2016, OD_2016_DO_TERAZ,

        // ROZRYWKI
        MUZYKA, TANIEC, TELEWIZJA, GRY, PRZYJEMNA_ROZMOWA, /*ODUZENIE,*/

        // PRACA
        PRACA_ZAWODOWA, PRACA_SZTUKI_WALKI, PRACA_NAD_KOBIETA, PRACA_NAD_DZIECKIEM, PRACA_NAD_BRACMI,

        // ZMYSLY

        // EMOCJE NEGATYWNE
        STRACH, LEK, ADRENALINA, NIEPOKOJ, TESKNOTA, /*SAMOTNOSC,*/
        GNIEW, ZLOSC, ROZPACZ, SMUTEK,
        ZAZDROSC,
        /*AGRESJA_FIZYCZNA, AGRESJA_PSYCHICZNA*/

        // EMOCJE POZYTYWNE
        /*SZCZESCIE,*/ RADOSC, KONTEMPLACJA, SPELNIENIE, SPOKOJ,
        CIEKAWOSC, ZASKOCZENIE,
        PODNIECENIE,

        // UCZUCIA NEGATYWNE
        ZREZYGNOWANIE,
        POCZUCIE_UTRATY,
        PRZYKROSC, POCZUCIE_WYKLUCZENIA, ZAGROZENIE,

        // UCZUCIA POZYTYWNE
        MILOSC, PRZYJAZN, BRATERSTWO, KOLEZENSTWO, POCZUCIE_SZCZESCIA, POCZUCIE_ZYSKU, POCZUCIE_SUKCESU,
        ZAPAL, PRZYJEMNOSC,

        // ZDOBYWANIE WIEDZY
        /*OCZY, PRZYCZYNA, REZULTAT, WNIOSEK,*/ SLOWO_PISANE, DOWODY_TEORII_NA_PLANSZACH, SLYSZANE_SLOWA,

        // ZAROBEK NIELEGALNY
        DILLERKA, ZLODZIEJKA, PRZEMYT, JAZDA_ZE_SPRZETEM,

        // KURESTWO
        INTERAKCJA_POLICJA, INTERAKCJA_ZAGRANICZNI, PUSZCZALSKOSC, ZDOLNOSC_KONFIDENTCTWO,

        LEKCEWAZY_MIEJSCE, LEKCEWAZY_OKOLICZNOSCI, LEKCEWAZY_OSOBY, LEKCEWAZY_WYSILEK,











        // *** *** *** *** *** *** *** *** *** PATOLOGIE *** *** *** *** *** *** *** ***
// PATOLOGIE ZWIAZKU
        STARY_MLODY, BURZUA_ULICA, NIESWIADOMY_SWIADOMY, SLABY_MOCNY, UZYWKI_BRAKUZYWEK, ZLO_DOBRO,
        LEKKOSC_TRUDNOSC, LATWOSC_ZERWANIA, ZDRADA, BRAK_CZASU, ODLEGLOSC,

        // PATOLOGIE_WSTEPNE_SWIAT
        SAMOTNOSC, ZWIAZEK_HOMOSEXUALNY, USZCZERBEK_NA_ZDROWIU, BIEDA,

        // PATOLOGIE_WSTEPNE_INFORMACJA
        /*BRAK_CZASU,*/ BRAK_DOSTEPU_DO_PLANSZY, BRAK_LUDZI, NIEMOZLIWOSC_MATERIALNEGO_ZNALEZIENIA_SIE, BRAK_MOZLIWOSCI_OCENY,
        OGOLNOSC,

        // PATOLOGIE_WSTEPNE_WIEDZA
        BRAK_INFORMACJI, BEZ_PRZYCZYNY, ZLE_SKUTKI, NIE_WYCIAGANIE_WNIOSKOW,

        // PATOLOGIE_WSTEPNE_BRAK_WSTYDU
        BRAK_WIEDZY, BRAK_DZIALANIA,

        // PATOLOGIE_WSTEPNE_REZULTAT
        OGROMNE_KONSEKWENCJE, BRAK_REZULTATOW,

        // PATOLOGIE_WSTEPNE_PRACA
        KARALNOSC, BRAK_WYKSZTALCENIA, BRAK_DOSWIADCZENIA, BRAK_UMIEJETNOSCI, ZADNYCH_ZNAJOMOSCI,

        // PATOLOGIE WSTEPNE_ZARABIANIE
        BRAK_PRACY, BRAK_PIENIEDZY,

        // PATOLOGIE WSTEPNE_SPORT
        NIESPRAWNOSC, NIEZDOLNOSC_DO_WYSILKU, BRAK_ZGODY_OTOCZENIA,

        // PATOLOGIE WSTEPNE_OSIEDLE
        INNE_MIASTO, ZLE_WYGLADA, BRAK_ZNAJOMYCH_W_SRODOWISKU, PRZECIWNY, KONFI,

        // PATOLOGIE WSTEPNE_DOPUSZCZENIE
        NIE_PATRZY, NIE_REAGUJE, NIE_USMIECHA, /*ZLO,*/ NIE_KOJARZY, WIDZI_PIERWSZY_RAZ, BRAK_WSPOLNYCH_ZNAJOMYCH,
        NIEBEZPIECZENSTWO, ZAJECIE, NIE_PODOBA_SIE, BRZYDKA, WSTYDZI_SIE, BRAK_EMOCJI,

        // PATOLOGIE WSTEPNE_KOBIETA
        NIE_STWORZENIE_POINTCUTA, NIEZLAPANIE_POINTCUTA, BRAK_POZNANIA, NIEDOPUSZCZENIE, BRAK_PARZONKA,
        NIESPODOBANIE_SIE, MINUS_GT_PLUS, ZAJETA,

        // PATOLOGIE UTRZYMANIA_SWIAT
        BRAK_ZNAJOMYCH, BRAK_ZWIAZKU, ZAGROZENIA, BRAK_ZRODLA_ZAROBKU,

        // PATOLOGIE UTRZYMANIA_INFORMACJA
        ZNIKNIECIE_INFORMACJI, BRAK_REZULTATU_INFORMACJI, BRAK_POTWIERDZENIA, NIEMOZLIWOSC_SPRAWDZENIA,

        // PATOLOGIE UTRZYMANIA_WIEDZA
        ZAPOMNIENIE, REGRESS_WIEDZY, UKRYWANIE_WIEDZY,

        // PATOLOGIE UTRZYMANIA_BRAK_WSTYDU
        NIEWYKORZYSTYWANIE_INFORMACJI, /*BRAK_DZIALANIA, NIE_WYCIAGANIE_WNIOSKOW,*/

        // PATOLOGIE UTRZYMANIA_REZULTAT
        NIE_PRZEWIDYWANIE, UTRACENIE,

        // PATOLOGIE UTRZYMANIA_PRACA
        BRAK_WYSILKU, NIE_UZYTECZNOSC, NIE_OPLACA, /*MINUS_GT_PLUS,*/
        NIE_PRZESTRZEGANIE_ZASAD, ZLA_ATMOSFERA, /*BRAK_REZULTATOW,*/ ZLE_STOSUNKI1VS1,
        REGRESS_UMIEJETNOSCI,

        // PATOLOGIE UTRZYMANIA_ZARABIANIE
        BIEDNY_SEKTOR, /*BRAK_WIEDZY,*/ DUZA_KONKURENCJA, BIEDNY_REGION,

// PATOLOGIE UTRZYMANIA_SPORT
        /*REGRESS_UMIEJETNOSCI,*/

        // PATOLOGIE UTRZYMANIA_OSIEDLE
        BRAK_CELU, NIE_DZIALA, NIE_KIBICUJE, NIELOJALNY, NIE_PRZESTRZEGA_ZASAD,

        // PATOLOGIE UTRZYMANIA_KOBIETA
        NIESPELNIENIE_OCZEKIWAN, NIEWSPIERANIE_PREFERENCJI, SPEDZANIE_CZASU_OSOBNO, /*ZDRADA,*/ BRAK_KONTROLI,

        // PATOLOGIE KONCOWE_SWIAT
        NIESZCZESCIE, ZLE_DOSWIADCZENIA, ZLE_WSPOMNIENIA,

        // PATOLOGIE KONCOWE_PRACA
        /*BRAK_PIENIEDZY,*/ BRAK_STABILIZACJI, ZMUSZONY_ZAGRANICA, /*BRAK_UMIEJETNOSCI, BRAK_WIEDZY,*/

        // PATOLOGIE KONCOWE_ZARABIANIE
        BRAK_MOZLIWOSCI_WYBORU,

// PATOLOGIE KONCOWE_SPORT
        /*NIESPRAWNOSC, BRAK_UMIEJETNOSCI, BRAK_WIEDZY,*/

        // PATOLOGIE KONCOWE_OSIEDLE
        /*BRAK_ZNAJOMYCH,*/ BRAK_SRODOWISKA, BRAK_KOBIETY, BRAK_DOSTEPU_SILNE_JEDNOSTKI,
        BRAK_THREAD_WHILE_LOOP_BLISKOSC_U, /*MARNOWANIE_CZASU,*/ BRAK_AKCEPTACJI, BRAK_DOSTEPU_PRZEWAGI,

        // PATOLOGIE KONCOWE_KOBIETA
        BRAK_CODZIENNEJ_BLISKOSCI, ZYCIE_W_SAMOTNOSCI, BRAK_DZIECI, PRZERWANIE_GENU,

        // PATOLOGIE GLOBAL_PLANSZA_LUDZIE
        MALA_DZIETNOSC, BLEDY_WYCHOWANIA, BRAK_MIESZKANIA,

        // PATOLOGIE GLOBAL_PLANSZA_PRACA
        BRAK_FIRM_NWD, BRAK_FIRM_WD, ZABURZONY_RYNEK_PLAC, OGROMNE_ZASOBY_LUDZKIE,

        // PATOLOGIE THREAD_WHILE_LOOP
        BRAK_THREAD_WHILE_LOOP_ZASIEG_WZROKU, /*BRAK_THREAD_WHILE_LOOP_BLISKOSC_U,*/
        BRAK_THREAD_WHILE_LOOP_BLISKOSC_K, BRAK_THREAD_WHILE_LOOP_EFEKTYWNA_GADKA,

        // *** *** *** *** *** *** *** *** *** CPUS *** *** *** *** *** *** *** ***
                // APPROACH
        SMIETNIIK_NA_BUZI_JUZ_DAWNO, ENK_1_2,
                // PLANSZA
        /*LUDZIE,*/ PRZYMUS, POTRZEBA, SCIEZKI, /*TRANSPORT,*/
                // POMAGAJACE
        MALA_TRUDNOSC, MALY_WYSILEK, MALA_DROGA, MALY_PRZYPAL, /*OSZCZEDNOSC_CZASU,*/ BRAK_SLUCHAWEK, WZGL_IZOLACJA,
        PRETEKST, /*KONTEKST,*/
                // M-W WCHODZISZ NA PLANSZE
        /*ZASIEG_WZROKU, INFORMACJE*/
                //MMWWP SONDA_OSOBY, SONDA_SYTUACJI
        SYTUACJA,
        UNIKALNA, CHCIANA, W_HOTMIEJSCU, DEFAULTOWA, RESTRYKCYJNA, KRYZYSOWA,
                // odrazu pochwycenie
        BEDZIE_CIEKAWIE,ANTY_PARTYZANTKA,

                // MM-WW-REZULTAT WSTANIE,PRZEJSCIE
        FOCUS, THREAD_WHILE_LOOP_BLISKOSC,
                // M-W PREFIX(PARAMS) =
        WIDZENIE_NA_ROZMOWA, REAKCJA, INFO_O_POINTCUT,
                // M-W METODYGADKI = NIEUSTANNA EFEKTYWNA_GADKA
        NIEUSTANNA_GADKA, EFEKTYWNA_GADKA, NASTAWIENIE_WZIECIE_KONTAKTU,
                // M-W WZIECIE_NUMERU, TEMAT PONOWIENIE, TEMAT PONOWIENIE =
        NUMER,

        // SYTUACYJNE
        /*PATRZY,*/ SIEDZI, SIEDZA, Z_KOLEZANKA, /*WZGL_IZOLACJA,*/

        // ESENTIAL CONDITIONS
        DOSTEPNOSC, /*BLISKOSC,*/ SZYBKOSC_CHODZENIA, /*INFORMACJA,*/
        ZASIEG_WZROKU, ZASIEG_JEJ_WZROKU,
        CZAS_START, CZAS_KONIEC,
        SRODOWISKOWE, STALE, RESTRYKCYJNE,
        // ESSENTIAL CECHY
        /*SPRYT, SZYBKOSC, SILA,*/
        // ESSENTIAL OSOBA
        STWARZA_POINTCUT, /*REAGUJE,*/

        /*ZLE_WYGLADA,*/ SWOJE_RZECZY,

        NIEPODBIJASZ,

        POTENCJALNA_PRZEWAGA, PODZIW_SZACUNEK,

        _1SPOJRZENIE, ENOUGH, GADAJA_ZE_SOBA, WIECEJ_NIZ_POPATRZENIE, PATRZYSZ,

        NIEDOSTEPNA, NIECHCE_SIE, STATYSCI, SZANSA, SAVE_TIME, PROC_30_DOBRYCH,

        TLUM, CISZA, MOZLIWE_SLUCHAWKI,

        PRZESKOCZENIE, INIT, X_100, X_1000,

        OGRANICZENIE_CZASOWE, PASS, BLISKO, KOMFORT, PRZYSZLY_SIE_POKAZAC,

        DLUGA_DOSTEPNOSC, BEZRUCH, /*KONTEKST,*/

        STREFY_PRZEGUBOWE_3, /*CISZA,*/ CHODZAC_ROZMOWA_UWAGA_NA_TOBIE, BIEDACY,

        ULOTNOSC, ZARAZ_WYSIADZIE, ZARAZ_WYCIAGNIE_SLUCHAWKI,

        TRAUTO, BAHNA,

        LEPSZA_OPCJA,

        SZCZYT, PRZYSTANEK, WEJSCIE, BLOKI,

        NAMIERZONA,

        /*OSZCZEDNOSC_CZASU,*/ MNIEJ_CZASU, BRAK_GLUPICH_UCZUC, GLUPIE_UCZUCIA, MOZLIWOSC_ZLAPANIA_WZROKU,
        NIETRZEBA_TRZYMAC_ORIENT, TRZYMASZ_ORIENT, MNIEJSZE_SZANSE, WIEKSZE_SZANSE, WIEKSZA_SZANSA_LINCZ, BRAK_CISZY,
        MUSISZ_DOGONIC, ZERO_LUDZI, BRAK_STATYSTOW_WOKOL, BRAK_KOMFORTU, IDZIE,
        SZANSA_NA_SPOTKANIE_WZROKIEM, WIDZIALA, WYCHODZI,
        SIEDZISZ, SIEDZIMY, WRAZLIWA, PATRZY_ULAMEK_SEKUNDY, POZNALES_KOGOS, MIEJSCE, SLUCHAWKI,
        CZORCIK, MIEJSCE_STALE, SZANSA_BECZKA_ZNAJOMOSC, SPECJALNE_NIEWIDZENIE, OLEWKA_PODBICIA,
        SLABY_FOCUS, OGLADANIE_RZECZY, ZAJETA_OSOBA_TOWARZYSZACA,
        OBSLUGA, GALERIA, SKLEPY_DLA_KOBIET,
        ZARAZ_STACI_FOCUS, ZARAZ_KTOS_WEJDZIE,
        IDA_KOLEZANKI, PROBUJE_SIE_POKAZAC, NIEPATRZY_W_OCZY_ALE_TWOJA_STRONE, PATRZY_W_OCZY_CZESTO, PIERSCIONEK_ALE_PATRZY,
        POKAZUJE_SIE,
        WYKAZALA_ZAINTERESOWANIE, MAM_CHLOPAKA, OPCJA_PARZENIE, DOBRA_JEDNOSTKA, NIE_PARZYSZ, PARZENIE, /*SRODOWISKO,*/
        THREAD_WHILE_LOOP_ANTYPUSTKA, ZOBOWIAZANIE_DO_GADANIA,
        TRANS, POPATRZENIE_X2,
        SKLEP, /*TRAUTO,*/ JALOWY_ON, RESTAURACJA, KLUB,
        IDZIESZ_NAPRZECIWKO, _2_WZROKOWE, WIDZISZ_SYTUACJE, BEST_POZYCJA,
        WIDZISZ_TYL, NIEPATRZA_GADAJA, PRZEWIDZIALES_DROGE,
        _3s, _2s, _1s, _30s, IDZIESZ_ZA_NIA,
        BEST_CASE, NORMAL_CASE,
        PODBIJASZ, BRAK_JAKOSCI_PLANSZY,
        PIERSCIONEK, NIE_DA_SIE_ZOBACZYC_PIERSCIONKA,
        DOPUSZCZA_ODPISUJE, DOPUSZCZA_MOWA,
        SZANSA_KONTAKT, SZANSA_POZNANIE,
        IDZIESZ_W_MIEJSCE_STALE, WIECEJ_OKAZJI_DROGA,
        SZYBKO, ODSTEP_0_5s, /*PRZEWIDYWANIE, REZULTAT,*/
        SZANSA_POKAZANIE_GADKI, SZANSA_POTENCJALNY_ZWIAZEK,
        /*NUDA,*/ MONOTONIA, KARA,
        NIEODPOWIEDZIALA, UCINA, LOOKING_FORWARD_NEVER_BACK, NIEODPOWIEDZIALA_NA_MIEJSCU,
        NAJWIECEJ_NA_MIEJSCU, ODPUSZCZSZ, WORST_CASE, PARTYZANTKA,
        BOISZ_SIE, NIEPRZYGOTOWANY,
        INTERAKCJA, KOJARZENIE_Z_DOBREGO, /*ZNAJOMI,*/ /*POTRZEBA,*/ WARTOSC, UNIKALNOSC_W_OTOCZENIU,
        OBECNOSC, PLANSZA,
        ZAUWAZYLEM, USLYSZALEM,
        PRZEWAGA_CZASU, PRZEWAGA_INFORMACJI, PLAN, DLUGOSC_DOSTEPU, BRAK_WYKONANIA_PLANU,
        NA_PLANSZY, WARUNEK, WIDZISZ_DZIALANIE,
        /*MODA, PRZEWAGA,*/ /*NUDA,*/ UCZUCIE, /*CIEKAWOSC, ZAZDROSC,*/ /*PRZYMUS,*/
        NORMALNA_SYTUACJA, ZLA_SYTUACJA, CHCESZ_NORMALNA_KOBIETE, WARUNEK_A, WARUNEK_B,
        WYCHODZISZ_Z_PRACY, SILY, ULICA,
        NORMALNE_MIEJSCE, NORMALNA_PORA, IZOLACJA_CZLOWIEKA, ZLY, DOBRY, WSZYSCY, ZLO_NA_CZUBKU_STOSU,
        /*WYSILEK_UMYSLOWY,*/ /*WYSILEK_FIZYCZNY,*/ DUZO_ZARCIA, WZROK, SAMOPOCZUCIE,


        STARCIE, DOMINACJA, RUCHANIE, W_TLE_DOSTEP,
        ZAGRANICZNI, BURZUAZJA, BIEGACZE, NIECHCACY_WPUSCIC,
        /*DOMINACJA,*/ GLUPIEGO_CZEKA_KARA, /*PRZEWAGA,*/ DOSTEP, HIERARCHIA, /*JEDNOSC_PRZECIW_ZAZDROSCI,*/ RYWALIZACJA,
        /*OGRANICZENIE_CZASOWE,*/ DNI, TYGODNIE, LATA , /*OBECNOSC,*/ /*DOSTEP,*/ POZNANIE_CZLOWIEKA_WADAMI, ENUM, ANTY_FEST, /*ANTY_SYSTEM,*/ ANTY_BURZUA, ANTY_KONFI, ANTY_POSLUSZNOSC, DEFAULT_ZACHOWANIE, DEFAULT_WARUNKI, /*STARCIE,*/ KTO_ZYSKUJE,
        SWOJA_EKIPA, PRZECIWNA_EKIPA, PSY, KAZDE_DZIALANIE_OCENIANE, PROAKTYWNOSC, PILNOWANIE_HIERARCHII, PILNOWANIE_PRZEWAG, WPROWADZANIE_ZASAD, ZMANIURAMI_PO_INFORMACJE,
        /*LUDZIE_ZA_TOBA,*/ /*WALKA_PIESCI, WALKA_SPRZET,*/ STANDARDY, /*PRAWO,*/ PRZEKONYWANIE,
        PRZESTRZEGANIE_STANDARDOW, PRZESTRZEGANIE_PRAW,
        MALY_DOSTEP, MALE_ZAGROZENIE, /*MALY_PRZYPAL, ZGODA_OTOCZENIA, */
        DOBRE_MIEJSCE, DOBRA_GODZINA, ZLAMANIE_ZASAD, ZGODA_GORY,
        /*DLUGA_DOSTEPNOSC,*/ PRZEKONANE_OTOCZENIE, /*LUDZIE,*/
        ZLAMANIE_STANDARDU, ZLAMANIE_PRAWA,
        POZBAWIANIE_AUTORYTETU, LUDZIE_WOKOL,
        /*OCZY,*/ USZY, CIERPIENIE, CIERPIENIE_DLUGOTERMINOWE, POZBAWIENIE_PRZEWAGI, KOSZTA, POZBAWIENIE_BEZPIECZENSTWA, POZBAWIENIE_DOSTEPOW, /*PRZEJEBANE,*/
        AUTORYTET,
        EKIPA_RYZYKO, EKIPA_WALKA, EKIPA_SPRZET,
        OGARNIECI_ZA_TOBA,
        GORA_ZA_TOBA, OWNER_ZA_TOBA,
        TWORZENIE_WARUNKOW, TWORZENIE_POINTCUTOW,
        EKIPA_DLUGA_DOSTEPNOSC,STWORZONY_WARUNEK, STWORZONY_POINTCUT, POINTCUT,
        BLISKIE_OSOBY,
        ZOBOWIAZANIA, OCZEKIWANIA, WYMAGANIA, CEL, /*ZDOLNY_DO_WALKI, ZDOLNY_DO_RYZYKA,*/
        WEJSCIE_KAZDY_KLUB, WEJSCIE_BOKS, WEJSCIE_SILKA, WEJSCIE_OSIEDLE,
        DZIALANIE_W_EKIPIE, KONTAKT_TEL, THREAD_WHILE_LOOP_PUSTKA,
        POTENCJALNA_IZOLACJA_WIELE_RAZY, POTENCJALNE_ZYSKANIE_PRZEWAGI,
        ZMARNOWANA_SZANSA, DUZO_IF_OW, KONDYCJA, WYCHOWANIE_NA_ULICY,
        POTENCJALNE_STARCIE, _01, BENEFICJENT, BRAK_ZYSKU,
        CZESTO_PATRZY, NIE_WIE_CO_ZROBIC,
        THREAD_WHILE_LOOP_ZRODLA_GADKI, THREAD_WHILE_LOOP_NADRZEDNY_FLOW_GADKI, THREAD_WHILE_LOOP_WEDROWKA_POKOJE,
        NADRZEDNY_FLOW_GADKI, ZRODLO_GADKI, OGRANICZENIE_UWAGI,
        NIEODZYWASZ_SIE, UCINASZ,
        UNIKASZ_WALKI, NEUTRAL, TOCZY_SIE_BEZ_INGERENCJI, POZA_HIERARCHIA_ROZMOWY, GADKA,
        KTOS_WAZNY, COS_WAZNEGO,
        DOMINACJA_W_ROZMOWIE, NAJBARDZIEJ_CIEKAWY_TEMAT, WEDROWKA_PO_POKOJACH,

        KONKRETNA_INFORMACJA, DOWOD, ILE_OSOB_WIDZI_SLYSZY, GODZINA, /*MIEJSCE,*/ SCIEZKA_CZESTOSC_UCZESCZANIA,
        ZNANY_NA_MIEJSCU, LATWOSC_SZYBKOSC_ODDALENIA, ACCESS_MIEJSCE_ULTRADOSTEPOWE, MOZLIWOSC_ZMIANY_GLOBALNEGO_POKOJU,
        KTOS_SZKODZI, TRACE, STARZY_LUDZIE, FESTY, ZAPIERA_SIE, ZAPIERA_SIE_RODZINA_PRACA, KLOTNIA,
        MOZLIWOSC_PRZERWANIA_MOWY, UPORCZYWIE_PRZERYWA, /*ZASZKODZIL,*/ KOLECZKO_WZAJEMNEJ_ADORACJI,
        ZLA_JEDNOSTKA, ZASIEG_ZMYSLOW, KOSA, NIEGODNY_POPATRZENIA, ROBI_ZDJECIA, MOZLIWOSC_PRZYPAL,
        /*CISNIE,*/ USMIECH_ZNIEWAZAJACY, CISNIE_MOCNO, BEKA, NIEZNASZ_GO, BEKA_Z_CIEBIE, SPOJRZENIA, GANGUS,
        _2SPOJRZENIA, DLUGO_PATRZY, ODPOWIEDZ,
        STARCIE_NA_MIEJSCU, AKCJA, KOMIN, /*FEST,*/ /*SILNY,*/
        CHRONI_FESTA, TWORZY_KOLECZKO_ADORACJI, WYLACZY_DOSTEP, WYKLUCZY_CIE,
        MOZLIWOSC_STRATY_DOSTEPU_MIEJSCA,
        MOZLIWOSC_PSOW, BLAD,
        BRAK_ZAKLECIA, PRZEWAGA_OPIERAJACA_SIE_NA_LUDZIACH, MOZLIWA_ULOTNOSC,
        NIEZNAJOMY, NIEWSTANIE_OBRONIC_PRZEWAGI,  BAZUJE_NA_PRZEWADZE,
        WADA, WADY, NEURAL, /*DOBRY,*/ BRAK_PRZEWAG, PRZEWAGA_LOCAL, PRZEWAGA_GLOBAL, BRAK_PRZEWAGI_X, MAM_PRZEWAGE_X,
        STALA_PLANSZA, WIELE_INTERAKCJI, WIELE_OSOB, OSOBA_ODSLANIAJACA_SIE,
        /*ZLODZIEJKA,*/ KIBICOWANIE, DOBRZE_ZMYSLY, /*SPORT,*/ FEST,
        ODSLANIA_SIE,
        WIDZISZ_ZASOB, WIDZISZ_BLAD, SONDA_KOGO,
        BLAD_POJEDYNCZY, BLAD_NIESWIADOMY_PRZYPADKOWY,
        BLAD_SPECJALNY, BLAD_LENISTWA,
        BLAD_ZLAMANIA_ZASAD,

        ZAGRANICZNI_CIEMNI, ZAGRANICZNI_JASNI, BURZUA_DZIALAJACA, BURZUA_NIESWIADOMA, DZIALACZE_PRZECIWNI, DUZI_TEMPI,
        SONDA_DZIALACZY,
        CZLOWIEK,
        NIEPRZYDATNY, SWOJA_OBECNOSCIA_POGRAZA, CENTRUM,
        OSIEDLE,
        DZIALAJACY,
        PO_EKIPE_NIEZDARZY, PO_PSY_NIEZDARZY, SAM_NIEJEST_WSTANIE_SIE_BRONIC,

        PRZEWAGA_IZOLACJI_LUDZI, STARE_GANGUSY_TEMPI_PODZIELENI, KAZDY_W_EKIPIE_CZEKA_NA_SZANSE,
        ZLODZIEJI_1_PROC, CZOLOWKI_5_PROC, KIBICOW_10_PROC, MLODYCH_30_PROC,
        CO_JEST, CZEGO_NIE_MA, PRACUJE_SIE_DLUGO_CIEZKO_MALO_OSOB_TO_MA_WARTOSC, MALO_CZASU_ULICA_MALE_SZANSE_WYROBIENIA,
        /*BRAK_CZASU,*/ ODBIJANIE, UZYWKI, OGARNIETA_JEDNOSTKA_RODZI_SIE_W_CIERPIENIU, LOKALNE_SRD_CZARY,

        /*NISZA, BOGATY_SEKTOR,*/
        INTERVIEW, KONKURENCJA, MULTICULTI, KORPO, MOZLIWOSC_MALO_PRACY, OPEN_SPACE, STALO_SIE, DWA_MIESIACE, SZUKASZ_PRACY,
        /*BRAK_PRACY,*/ PRACA_NA_ETACIE, MANAGER, OKRESLAJACY_BUDZET, ZARZAD_FIRMY, OWNER_FIRMY, OWNER_KORPORACJI,
        SPELNIENIE_WYMAGAN, POPYT, ODZEW_HR, POZYTYWNY_FEEDBACK_INTERVIEW, WYGRANIE_Z_KONKURENTAMI, SCREENING_POZYTYWNY,

        PROJEKTY, MANAGEROWIE, TECHNOLOGIE, /*LUDZIE,*/
        KONFIDENCI, ZAWISTNI, CZYCHA_NA_BLAD, DZIWNA_PASJA,
        TECHNICZNOSC, STABILNY,
        /*STOSUNKI_1vs1,*/ /*ATMOSFERA,*/ /*UZYTECZNOSC,*/ MANAGO_DOBRA_OPINIA,
        OPLACA_SIE,
        DOBRY_PROJEKT, SZCZEGOLOWE_REQUIREMENTY, PROJEKT_UZYTECZNY, NOWE_NARZEDZIA, MANAGO_TECHNICZNY,
        UTRZYMANIE_PRACY,
        STRAZNIK_PRAWA, FINE, KLIENCI, TWORZYSZ_PROBLEMY, PSUJESZ_ATMOSFERE,
        ZASOB_ZYCIE_PRYWATNE, ZASOB_CZAS,

        TASK, ZEGAR, DATA, POPRAWNOSC_POLITYCZNA,
        WESZLES_DO_FIRMY,
        TEMPO_PRACA, GODZINY_PRZYJSCIA, DLUGOSC_PRZERWY, SCINANIE, STRATA,
        ZALEZNY_TASK, NIEPOKOJACE, PROGRAMISTA, PASJONAT, NIUNIUS, NIEWYKONANIE,


        TEZYNA_FIZYCZNA, UBRANIE, OSOBOWOSC, WARTOSCI_ZYCIOWE, /*SRODOWISKO,*/ SPEDZANIE_WOLNEGO_CZASU, RODZENSTWO,
        PRZECIWNOSCI, WARUNKI_OSIAGNIETE, WARUNKI_POCZATKOWE, /*CZAS,*/ CZYN,

        MONOSRODOWISKO, BRAK_STRESU, BRAK_TRUDNOSCI, /*KOMFORT,*/ /*BEZPIECZENSTWO,*/ WCZESNIE_ZWIAZEK, ZAJECIE_SIE_LOKALNYMI_SRPAWAMI,

        WARUNEK_UTWORZENIA_SIE_MIASTA,
        /*PRACA,*/ RDZENNI,

        /*OSOBOWOSC,*/ /*WIDZISZ,*/ SLYSZYSZ, CZUJESZ, Z_KIM_PRZYSTAJESZ, PRAKTYKA,
        CHARAKTER, /*CIERPIENIE,*/ CIEZKA_PRACA, TRUDNOSCI,
        UMYSL, PRACA_UMYSLOWA, CZYTANIE,
        FIZYCZNE, MAX_WZROKU, BIEGANIE, ROWER, BOKS, CIEZARY, PLYWANIE,

        /*CEL,*/ /*ZARABIANIE,*/ WYCHOWYWANIE, RDZENNA_LUDNOSC, PATOLOGIA, MLODE_KOBIETY_CHCACE_RODZINY,

        PATRZENIE_W_OCZY, OBELGI_WYSOKA_CZESTOTLIWOSC, OBELGI_W_PETLI, UKAZANIE_WAD, WYSMIANIE, WYSMIANIE_NAJBLIZSZYCH, UKAZANIE_WAD_NAJBLIZSZYCH,
        POBICIE_PRZY_ZNAJOMYCH, POBICIE_PRZY_RODZINIE, POBICIE_ZNAJOMYCH, POBICIE_RODZINY, USZCZERBEK_ZDROWIE, /*STRATA_HONORU,*/
        POPCHNIECIE, LEPIEC, STRZAL, KILKA_STRZALOW, BICIE_DO_UPADKU, BICIE_DO_UTRATY_PRZYTOMNOSCI,
        GLOWA_O_POWIERZCHNIE, KOPANIE_KONCZYNY, KOPANIE_BRZUCH, KLEPANIE_KARK,
        CIECIE_MIEJSCA_NIEZAGRAZJACE, CICIE_MIEJSCA_WIDOCZNE, CIECIE_MIEJSCA_ZAGRAZAJACE,
        WYLACZENIE_SRODOWISKA, WYLACZENIE_KOBIETY, WYLACZENIE_ZAROBKU, KAZDY_SPOTYKA_BIJE, KAZDY_KTO_SIEDZI_POJECHANE,

        DUZA_PRZEWAGA_STARCIA, DUZY_POSLUCH, DUZA_PRZYCHYLNOSC,
        TWORZENIE_ZARTY, TWORZENIE_MODY, ZBIERANIE_WARTOSCI,
        ZDOMINOWANIE,
        RESTRYKCJA, MOCNA_RESTRYKCJA, SREDNIA_RESTRYKCJA, WIEDZA_GDZIE_JAK_UDERZYC, STWORZENIE_WARTOSCI, ZEBRANIE_PRZEWAGI,
        ZDROWOTNE_KASOWANIE_JEDNOSTEK, DOSTEPOWE_KASOWANIE_JEDNOSTEK,
        OK, KUP_COS, WYPAD, SZPITAL, MEZCZYZNA_Z_KOBIETA, UMIE_BAJEROWAC, DOSTEP_OGRANICZONY,

        KASA, KOLEJKA, UJSCIE,

        CZOLO, OGARNIECI, MOCNI_NIE_LICZACY_SIE, CHETNE_PIONKI, PIONKI, MLODE_PIONKI,
        /*FEST,*/ BANAN, SYSTEMOWY_BURZUJ, WYGODNIS,


        OSIEDLOWY_BURZUJ, OSIEDLOWY_WYKRECONY, OSIEDLOWY_CASUAL, SPORTOWY_FEST,
        OSIEDLOWY_NORMAL, OSIEDLOWY_OGARNIETY, OSIEDLOWY, OSIEDLOWY_SLABY,
        BIEGACZ, PATOLOG, DIL, ZLODZIEJ,
        WIECZNY_IMIGRANT,
        RDZENNY_GLUPI, RDZENNY_DOBRY,

        RUDZI, CYGANIE,


        PRZEMYSL, HUTNICTWO, SPAWALNICTWO, WYDOBYCIE_SUROWCE, PRZETWORSTWO_SUROWCE,
        BUDOWNICTWO,

        KASJERKA, MAGAZYN,
        FRYZJERKA, KOSMETYCZKA, MAKIJARZYSTKA,
        HOTEL, GASTRONOMIA, OCHRONA,
        NAUCZYCIEL,
        KIEROWCA, MOTORNICZY,
        KSIEGOWA, HR, MECHANIK, ELEKTRONIK, INFORMATYK,

        SAMA, /*SIEDZI,*/ STOI, CHODZI, MALO_OSOB, POPATRZYLA, MIEJSCE_OBOK, /*IDZIE,*/ IDZIE_WOLNO, ZART, NA,
        ZNASZ, KILKA_PARZONEK,

        UNIKALNA_JEDNOSTKA, UNIKALNY_WARUNEK,
        MAKSYMALNIE_ULATWIASZ,

        // GADANE
        TWORZY_NADRZEDNY_FLOW, TWORZY_ZRODELKO, AKTYWNY_NA_ANGAZ, ODPOWIADA_NA_ANGAZ, SIEDZI_CICHO,

        MIEJSCE_HIERARCHIA,

        CHETNY_BOJKA, AGRESJA_CZYNNA, ODPORNY, ZADUFANY_W_SOBIE,

        POKONANIE_DYSTANSU,

        STATYSTA, TURYSTA_ZAGRANICZNY,
        STARY,
        BURZUJ_NIESWIADOMY, BURZUJ_DZIALACZ,


        LOKALNY,
        MLODY, SREDNI_WIEK,




        CZORT, OSIEDLOWA_KARYNA, OSIEDLOWA_KSIEZNICZKA, OSIEDLOWA_AGRESORKA, OSIEDLOWA_NORMALNA, OSIEDLOWA_DOBRA, OSIEDLOWA_SWIATOWA,
        BURZUA, KUJONKA, ZBYT_WRAZLIWA, ZWYKLA_FEST, WIESNIARA,
        SWIATOWA_DOBRY_DOM,

        MOZAIKA,
        CHOROBOWE, ODPOCZYNEK, /*STRATA_CZASU,*/ WKURWIENIE, STRES, INTERAKCJA_Z_FESTAMI,
        CONTINUE_NUDA, SPOTKANY_ZNAJOMY,
        MEZCZYZNA, /*KOBIETA,*/
        ROZMIAR, CZYNY_DZIALANIA, LADNA,

        _1_RANDKA_KONIEC, _100_CHLOPAKOW,

        NUDA_W_ZWIAZKU, PROBLEMY_KAZDEJ_KOBIETY, CHWIEJNOSC, UTRZYMANIE_RELACJI,

        /*PUSTKA,*/ RELACJA, OSOBA, ZDOLNOSC_ATAKU,

        NIENAWISC_FESTOW, STOISZ, MIEJSCE_PRZECHODNIE,
        LEKKIE, MOCNIEJSZE,
        /*MIESZANIEC,*/ SILNIEJSI,
        ANTY_PUSTKA, ANTY_NUDA,
        OBRONA, NIEDZIALAJACY, AGRESOR, ANTY_NORMALNOSC, DEFAULT, NIEODPOWIADA,
        PASJA, TYLKO_TO, STYL_ZYCIA, ODERWANIE_OD_RZECZYWISTOSCI, BRAK_CHETNOSCI, MARZY_OBCOKRAJOWIEC,
        TWORZENIE_WZAJEMNEGO_CIERPIENIA, /*EMOCJE_ZE_ZLA,*/ POCZATEK, KONIEC, ILOSC_OSOB, CZESTOTLIWOSC,
        BRAK_CZASU_CODZIENNE, BRAK_CZASU_ROCZNE, ZERO_ZYSKU_ZYCIOWO,

        NIEPRZEKUPNY, POBOZNY,
        BAWMYSIE_JEGO_PODKOPAC, WALKA_Z_W8C, WZIAC_MU_WSZYSTKO,

        PODBICIE, STWORZENIE_SYTUACJI, GOTOWY_NA_STARCIE,
        SZANSA_SONDA, SZANSA_INFORMACJA,
        NIEPRZECIETNE_RZECZY, NIE_REGENERUJE_SIE, TOKSYCZNY_ORGANIZM, SIEROTA,
        END_CASE_SILNY, WIEDZA_RYNEKPRACY, WIEDZA_PRAWO, WIEDZA_ULICA, WIEDZA_KOBIETY, WIEDZA_ZAWOD, WIEDZA_LUDZIE_GENY, WIEDZA_LUDZIE_CHARAKTER, WIEDZA_SPORT,
        DOBRE_ZYCIE, Z_KAZDEGO_NARODU, KLUCZ_ZYCIOWY, PODSWIADOMOSC,
        BRAK_CIAGLOSCI_OTOCZENIA, OD_ENDCASE_DO_ENDCASE,
        SILA_RZADZI, FEST_RZADZI, MOWI_SZYBKO, CHECI, PRACOWITOSC, CIEZKI_WYGLAD, _100PROCENT_WYSILKU_10PROCENT_OTRZYMUJESZ,
        CALE_ZYCIE_CIERPIENIE, STARZEJESZ_SIE, MIESZKANIE_300TYS_WYPLATA_3TYS, ZDANY_TYLKO_NA_SIEBIE, Z_GORY_PRZEGRANY,
        _1_OSOBA__DUZO, TOZSAMOSC_RASOWA, DOSTEP_DO_WIELU_PLANSZ, NA_HUCIE_30_LATKI_BOJA_SIE,
        STARA_BAHNA, SIEDZENIE_PRZED, SIEDZENIE_OBOK, STOISZ_NAD_SIEDZENIEM, STOISZ_OBOK,
        OPCJA_PRZEJSCIE, NIE_DOSTAJESZ, NIE_FINALIZUJESZ, FRAJER_DOSTAJE, MESKA_PROSYSTUTKA, JA_DOSTAJE,
        DZUNGLA, KTOS_CIEBIE_LUB_TY_NIEGO,
        PODROZE, /*WYGODY,*/ PRZEKAZANIE_ZLEGO_GENU, NABICIE_KABZY_KAPITALISCIE,
        G41, TM, TMTR, PK, AGH, BKS_HTK, BXRNIA, GRPL, CL, BBH,
        CHOROBA_SIEROCA, LOPATKSY, POSTURA_50KG, ON_LICHY_JEST,
        ROZWALENIE_SWIADOMOSCI, NAJNIZSZY_POZIOM_WARSTWY, ZWIAZEK_Z_ZAGRANICZNYM, STARA, MLODE_KOBIETY, MALE, PATOLA_DOSTEPOWA,
        BRAK_POKAZANIA_SIE, MOZLIWOSC_WYCHOWANIA, PLUS_30, KILKA_NIEUDANYCH_ZWIAZKOW, BRAK_OPCJI, WZIETE_NA_POZIOMIE_SZKOLNYM,
        MILION_ADORATOROW, MALO_PRACY, ZLY_CHARAKTER, ZEROWE_SZANSE, SKRESLA_ZA_1_NIEDOCIAGNIECIE, WYJEBKA_NA_WLASNE_ZMECZENIE,
        SLABSZA_PRZEWAGA_ULEGA_MOCNIEJSZEJ_W_MOMENCIE_PRZY_WARUNKACH, ZADNEJ_LITOSCI,
        PATRZENIE_MONITOR, DAILY, WEEKLY, COMMITY,
        NIECHCIANE_DZIECKO, DOM, CODZIEN_OD_POCZATKU, WALKA_ZAGRANICZNI, CHETNOSC, PRZEJSCIE, ZWIAZEK, EMIGRACJA, PRACA_KRAJ,
        NIKT_NIE_REAGUJE, ZASOB,
        IDZIESZ_ZAWRACASZ, PRZECIWNY_PRZYSTANEK, SIEDZISZ_PRZEJSCIE, ONA_SWOJE_GRONO, RODZICE,
        WIDZISZ_KONTEKST, WIDZISZ_POWIAZANIA, WIDZISZ_WYDARZENIA_PRZESZLOSC, WIDZISZ_KRAJOBRAZ,

        // STAN
        STERYD, ZIELSKO,
        TLEN, SEN, CHOROBA, KONIK, CHEC_REGENERACJI, CHEC_ZBICIA_NIEPOKOJU, COUNTIOUS,
        ZLE_SAMOPOCZUCIE, SAMOPOCZUCIE_FAZA,
        TRACISZ_WZROK, WZROK_NIEOSTRY, KREW_SIE_CHOWA, NADWRAZLIWY_SLUCH, BRAK_SCHIZMY,
        BRAK_MIESNIA_NA_CZOLE, ZLY_BLEDNIK, NIEDOSTRZEGANIE_PIEKNA, NIEDOSTRZEGASZ_REALNOSCI,
        BRAK_WYOBRAZENIA, BRAK_PAMIECI, BRAK_NASTAWIENIA, NIEZDOLNY_RYWALIZACJA,
        MIAZDZY_GARDLO, NIEZDOLNY_SKUPIENIE, SERCE_SLABE, NIEODPOCZYWASZ, /*BRAK_EMOCJI,*/
        BRAK_KOJARZENIA, ZA_USZAMI_ZLE, BRAK_MOTOREK, BEZBRONNY, /*NIEZDOLNOSC_DO_WYSILKU,*/
        CPU_NA_USZACH, BRAK_WNIOSKOW, NIC_SIE_NIECHCE, NIEPAMIETASZ_HISTORIA, NIEWIESZ_NIC,
        SPISZ, BRAK_ORIENTU24, MROWIENIE,

        BRAK_CIERPIENIA, NOWA_OSOBA, WYZSZE_DOBRO, PROWOKUJE, CISNIE, WYPROWADZA_Z_ROWNOWAGI, KTO_SZYBSZY_TEN_LEPSZY,
        STRATY_MATERIALNE, STRATY_MORALNE, PRZERWA_KONTUZJA, USUNIECIE_Z_PLANSZY,

        RESET, ZMIANA, NIE_PRZEWIDZISZ_PRZYSZLOSCI,
        DEFICYT_WSROD_STARYCH, MALE_ZRODLO_MLODYCH_KOBIET, POCIAG_DO_ZAGRANICZNYCH, ZMIANA_SYTUACJI_DEFAULTOWEJ,
        DOBRA_PLANSZA, KOMPLEMENT, DRUGI_RAZ, KONTAKT, UWAGA_NA_TOBIE, ROZWALENIE_CISZY,
        POPRUSZONE_NA_MIEJSCACH, X,
        BRAK_ROZRYWEK, BRAK_DOBRYCH_UCZUC, PUSTKA, DEFAULT_SYTUACJE,  SRODOWISKO_SYTUACJE,
        ZEROWY_DOSTEP, NIEPATRZY_GLOBALNIE, ZAMKNIETY_W_SWOIM_POKOJU, BAHNA_1_DO_2_KOBIET, POL_GODZINY_1_DO_2_KOBIET,
        KTOS_MI_COS_ZROBIL,
        WLASNE_TERYTORIUM, CHODZENIE_WSROD_PUSTKI, BRAK_REKACJI, PRZEWAGA_ZROBIONA_NA_KRZYWDZIE_LUB_KURESTWIE,
        NIKOGO, KTOS, ZLE, BIJESZ_KTOS_MOZE_ODDAC_MOCNIEJ, WSZEDZIE_OBCY_GADZIO,
        PYSZNY, WYZSZOSC_NAD_INNYMI,

        MORDERCY, DLUGO_WIEZIENIE, BUDUJACY_HIERARCHIE_DECYZYJNI, RUMUNI, BANDYCI, NIESPRAWIEDLIWI, AGRESYWNI, ILE_SIE_DA,

        NIE_DEFAULTOWA_SYTUACJA,

        Z_RODZINA, MALE_SKUPISKO_LUDZI, PORA_ROKU, ZOBACZENIE, END_CASE, OBJECIE_POCZATEK_KONIEC, PRZEWIDZENIE_KONSEKWENCJI,
        SAMOCHOD, CZARNA_TOGA_SEDZIOWSKA, NIEBOISZ_SIE_WYJSC, NIEBOISZ_SIE_STARCIA, NIEBOISZ_SIE_NIESPRAWIEDLIWYCH_PRZEWAG,
        PRIORYTET_WYCHODZENIE_U_SIEBIE, CECHY_WSZYSTKIE_NABYTE, ZNAJOMI_OD_SZKOLY, UTRZYMANE_PRZEWAGI_OD_SZKOLY,
        STARSI, WYKLUCZENIE_ZE_SRODOWISKA, KORZYSCI, FALSZYWE_KORZYSCI, WYKORZYSTUJ, WYJSCIE, PIERWSZY_KONTAKT, NASTEPNY_KONTAKT,
        ZNA, WIE_ZE_WARTO, CZYTAJ_DOKUMENTACJE_MYSL,

        BOL, RANY_ODNIESIONE, REGENERACJA, WROG, JEGO_KOLEDZY_TWOI_WROGOWIE,
        DZIECIAK, PIERWSZA_TRUDNOSC_PODDANIE,
        MAGICZNE_ZAKLECIE, POJECHANIE_NA_PRZEWADZE, SKAZYWANIE_NA_CIERPIENIE, UKRYCIE, CHCIWOSC,
        PODZIELENIE_SIE_PRZEWAGA, WYZWOLENIE_Z_CIERPIENIA, PODNIESIENIE, UJAWNIENIE, WYJEBANIE_ZLA_KONTRA,
        PYTANIA, PRZEPLYW_WIADOMOSCI, FEEDBACK_INNI, PROGRESS_ILOSCIOWY, PROGRESS_JAKOSCIOWY,

        WDUPCANIE_WSZYSTKICH, ROBIENIE_CIERPIENIA, WIECZNA_PRZEGRANA, OBOWIAZEK_ZLA, KAZDY_KAZDEGO_AGRESJA_DLA_EMOCJI,
        OSZUKAC, MALYM_WYSILKIEM_NAJWIEKSZA_KRZYWDA, SLUCHAJ_KOLEGOW, PRZEWROTNE_FARYZEJSKIE_SUMIENIE, ZAWISC, KRZYWDA,
        NAKLEJ_NALEPKE, WDUPC_ZAKLECIEM, PRZEKONYWANIE_OTOCZENIA_PRZECIW, WYJEBAC_ZDJECIA, PRZESTRZELIC,
        ZWYZYWAC, OBGADAC, POBIC, SHANBIC, TEMPIENI_BYLI,
        BEZ_WSTYDU, BEZ_ZASAD, BRAK_SUMIENIA, ULEGLI, UZALZENIENI, WYKRECONE_SZCZURKI, OFERMY,
        KONTRA, WYGRANA,

        GLOSNO, UJAWNIC, SPRAWIEDLIWIE, BRAK_UZYWEK, USWIADOM, WIELKA_PRACA_ROBI_PRZEWAGE, MYSL_SAMODZIELNIE, MADRY,
        SUMIENIE, BRAK_PRZEWAG_NA_STARCIE, WSPARCIE, POZBAWIENIE_PRZEWAG_NIESPRAWIEDLIWYCH,
        POBIJ_JAK_NAJWIECEJ_OSOB, ZDOBADZ_JAK_NAJWIECEJ_PRZEWAG,

        OGROMNY_WYSILEK, ULTRA_OCZEKWIANIA_Z_KAPELUSZA, OCZEKIWANIA_ULTRASZCZEGOLOWA_WIEDZA_NT_SYSTEMU_Z_KTORYM_NIEMIALES_DO_CZYNIENIA_WCZESNIEJ_NIEMOGLES_MIEC_POJECIA_JAK_DZIALA,
        DAJ_ULTRA_SUPPORTOWE_NAJGORSZE_TASKI, IFLYRES2, PELNY_SUPPORT, UNIZ_WYKONANIE_ZADANIA, TO_BYLO_LATWE,
        CIAGLE_PODWYZSZANA_POPRZECZKA_JEDNOCZESNIE_INNE_PROBLEMY_KAZDEGO_TASKU, KAZDY_BLAD_KARA, KAZDE_PYTANIE_EWALUOWANE,
        ZLY_FEEDBACK_GDY_PYTASZ, INFORMACJE_ODRAZU_KRAZA, OCENA_TYLKO_WEDLE_ZLEGO, OCENA_CZEGO_NIE_ZROBILES,
        FARMAZON24_7, PIASKOWNICA, MALY_RUDY_FEST_GITARA_DLUGIE_WLOSY, IGNORANT_MALE_DZIECKO,
        MOWIENIE_MYSL_ROB_PROBOJ, NIE_MOWILEM_ABYS_TAK_ZROBIL, _100PROCENT_UZALEZNIENIE,
        WCHODZ_ZYCIE_PRYWATNE, ZLAMANIE_WSZELKICH_ZASAD_MANAGERSKICH, ROBOTA_LEZY, NASTEPNIE_POWOLYWANIE_SIE_NA_SZCZEGOLIKI,
        RZUCENIE_NA_TASKI_BEZ_PRZYGOTOWANIA_PRACOWNIKA, BRAK_MOZLIWOSCI_ESTYMOWANIA, ZABIERANIE_CZASU_OSOBOM_ZESPOLU,
        KAZDY_TASK_NOWY_BRAK_NOWY_PROBLEM, DELAY, ZLA_OCENA_Z_JIRY, NIEDZIALAJCY_KOMPUTER,

        WDUPCENIE_JAKNAJWIECEJ_OSOB_W_BIEGANIE, WDUPCENIE_JAKNAJWIECEJ_OSOB_W_CPANIE,
        POSIADACZ,PRYWATNY_FOLWARK, SUPERPOZYCJA,

        DOBRE_SERCE, WARTOSCI_RODZINNE, KOBIETA_DIAMENT_ODDANA_RODZINIE,
        WYDAWANIE_WYROKOW,
        WSPIERAJ_UCZ_ZAGRANICZNYCH, DAJ_DEVELOPMENT_ZAGRANICZNYM, KARC_POLAKOW, DAJ_SUPPORT_POLAKOM,
        ORIENT_RZECZY_WARTOSCIOWE, DZIALANIE_RZECZY_WARTOSCIOWE,
        WALKA, UTRZYMANIE_PRZEMOCA, UTRZYMANIE_EMOCJAMI, REWIR_ULICA, ARCY_KROL_CIERPIENIA,
        WYSMIEWASZ_ROBIENIE_ZDJEC,
        LUDZIE_RODZINA, LUDZIE_PRACA, LUDZIE_DZIELNICA, ZNAJOMI_DZIELNICA, PRZYJECIE_DO_WIADOMOSCI_BEZ_ROZKMINIANIA_NA_ULICY,
        MUSI_CI_SIE_CHCIEC, CONAJMNIEJ_2H, WALKA_O_WZGL_IZOLACJE,

        NIE_WYKORZYSTUJA,NIE_ZNAJA,WZGLEDNA_IZOLACJA_RDZENNI,ZRODELKO,ZEZWOLENIE_NA_GNOJENIE_INNYCH,
        PRZEWAGA_EKIPY_SPRZETU,ALL_DANY_OBSZAR_DO_ZRODELKA, WSZYSCY_SIE_ZNAJA, BEZ_PIENIEDZY, SLABI,

        ZLO_KRAZY, SWIADOMY_WLASNEGO_TERYTORIUM, SONDA_PRZEWAG, SONDA_CZYNOW,
        BIBLIA, MORALNOSC, SPRAWIEDLIWOSC ,PRZEWAGA_NA_SWOJA_STRONE,
        CZYNY_PRZECIW_TOBIE, SILA_PRZECIW_NIEMU, GNOJA,
        KONTUZJA, /*CIERPIENIE,*/ ORIENT, MIEJSCE_PRZESTRZEGANIA_PRAWA, SILA_SPRAWCZA, UKRYCIE_PRAWDY_PRZED_FESTAMI,
        AKTYWNA_WALKA_ZE_ZLEM, STOZEK_SZCZEGOLU, SUBSCRIBES_INFORMACJE, BLISKOSC, TELEFONY,
        WYMAGANIE_DZIALANIA_DLA_ZLA, GNOJ_POSTRONNYCH, GNOJ_EKIPA, UNIZAJ_CZYNY, GNOJ_EKIPA_NIZSI_OD_CIEBIE,
        WALKA_Z_FESTAMI,

        EMOCJE_FIRST, HIERARCHIA_FIRST, ZMIENNOSC, /*WRAZLIWOSC,*/ WOLNOSC,

        /*NIESWIADOMOSC,*/ DZIECKO, BRAK_INFORMACJI_OTOCZENIE,
        NIE_WIDZI_ZAGROZEN, NIE_ROZUMIE_PRZYCZYN_SKUTKOW, NIE_WYCIAGA_WNIOSKOW, NIE_KOJARZY_FAKTOW,
        NIE_DOSTRZEGA_SZCZEGOLOW, NIE_WIDZI_KONTEKSTU, BAGATELIZUJE_INFORMACJE, IGNORUJE_INFORMACJE,
        NIE_WIDZI_OKAZJI, NIE_STWARZA_OKAZJI, NIE_WYKORZYSTUJE_OKAZJI,

        TWORZY_SOBIE_PROBLEMY_ZAMIAST_ROZWIAZYWAC, NIE_WIDZI_SWYCH_BLEDOW, POWTARZA_BLEDY, NIE_PAMIETA_BLEDOW, LEKCEWAZY_BLEDY,

        JEDNO_MOWI_DRUGIE_ROBI, ODERWANY_OD_RZECZYWISTOSCI,
        BRAK_KONSEKWENCJI, BRAK_SZACUNKU_DO_LUDZI, BRAK_SZACUNKU_DO_ZASAD, BRAK_SZACUNKU_DO_CZYNOW,

        /*PIERWSZA_TRUDNOSC_PODDANIE,*/ NIE_UMIE_PRACOWAC, PRACUJE_GDY_WYGODA_ZAPEWNIONA,
        NIEZDOLNY_DO_WYSILKU, NIEZDOLNY_DO_CIERPIENIA, ZEROWA_SILA, NIEZDOLNY_DO_WALKI,
        BOI_SIE_PRAWA, BRAK_SILY_SPRAWCZEJ,

        /*BRZYDKI,*/ EMOCJE_ZE_ZLA, DZIWNE_HOBBY, DZIWNY_SYSTEM_WARTOSCI, KOMPLEKS_WZGLEDEM_LEPSZYCH, PRZECIW_LEPSZYM,
        /*KOLECZKO_WZAJEMNEJ_ADORACJI,*/ PODLIZYWANIE_SIE,

        BRAK_ZOBOWIAZAN, BRAK_WYMAGAN, BRAK_OCZEKIWAN,

        BRAK_WSTYDU_WEW, MULTIKULTI_OK, MIECZAK, NIE_DOTRZYMUJE_TERMINOW, FALSZYWY, NIE_UMIE_KLAMAC,


        BRAK_SENSU_INTERAKCJI,  FESCIARSKIE_BEZBARWNE_TEMATY, BEZSENSOWNE_KLUTNIE,
        NUDNE_ZYCIE_PRZEWIDYWALNE_BEZ_EMOCJI, IMITACJA_ZYCIA, BYLE_CO, BYLE_GDZIE, BYLE_Z_KIM,

        CIEKAWSKI, LUBI_WYGODY, LUBI_PRZYJEMNOSCI, MIESZANIEC, KONSTRUKTYWNA_KRYTYKA_JAKO_WYZWISKO,
        /*GNIEW,*/ BRAK_OBIEKTYWNEJ_OCENY, BIZNES_PRYWATNY_FOLWARK_SUPERPOZYCJA,

        TWARDOGLOWY_LUB_MIEKKOGLOWY, /*SPOKOJ,*/ DYKTATURA_SZCZESCIA_ZERO_WYSILKU_KONFLIKTOW,

        SZUKAJ_ZASTEPSTWA, ZWRACAJ_WSZYSTKO_NA_REVIEW, NIE_PYTASZ_NIE_WIESZ,
        BRAK_DOBREGO_WYCHOWANIA, BRAK_REWIRU, BRAK_POZNANIA_OTOCZENIA, BRAK_NORMALNYCH_EMOCJI, BRAK_KONKURENCJI,
        CHEC_BEZPIECZENSTWA, BRAK_SILNYCH_JEDNOSTEK, BRAK_WLASCIWEJ_OCENY, KOLKO_WZAJEMNEJ_ADORACJI,
        POZNANIE_WARTOSCI_PIENIADZA, FAZA_Z_NAUKI, FART, DOBRY_ZAWOD, NIEPOSLUSZONSC_B, SILNIEJSZY_B,
        JUMA, POZNANIE_NAUKI, PRZYCHYLNOSC_BOGA, WYCHOWANIE_POD_KLOSZEM, ZLE_WYCHOWANIE, ROZPASANIE_ROZPIESZCZANIE,
        SLABI_RODZICE, BRAK_POZNANIA_NAUKI, BRAK_SPORTU, DOBRE_CZYNY,

        KAZDE_DOBRO_NA_DOL, KUMULUJACA_SIE_PATOLOGIA, BEZPRZYPALOWE_MIEJSCE, OPPONENT_NIEPRZESTRASZONY,
        DOBRE_WYCHOWANIE, SILNI_RODZICE, ZARADNOSC, SZCZESLIWE_DZIECINSTWO, KALKULACJA_FIRST, KONSEKWENCJA,
        REWIR, ZNAJOMOSC_OTOCZENIA, NORMALNE_EMOCJE, PRAWDZIWA_PASJA, WLASCIWA_OCENA, MOCNA_JEDNOSTKA, SILNA_JEDNOSTKA_FIRST,
        DOBRE_WYBORY, OSIAGNIETE_CELE, SPRZET, ZALEZNOSC_OD_EKIPY, ZLA_PRACA, NIESTABILNOSC_MATERIALNA, SLABA_MANIURA,
        UZALEZNIENIE, BRAK_PERSPEKTYW, POWIE_DO_KOLEZANKI, KOMBINACJA_TEMATOW, TOPICS, ZNAJOMI_PRZESTEPCY,
        ULGA_DLA_SWOICH, PODKOPANIE_INNYCH, SILA_SPRAWCZA_W_MIEJSCU_POD_WARUNKAMI, OCHRONA_SWEJ_POZYCJI,
        PRZEWAGA_SILY, ATRAKCYJNA_EGOISTKA, BEZKARNOSC, NIE_PAMIETA_SWOICH_OFIAR,

        WARTOSC_DODATNIA, KULTURA, ULEGLOSC_WZGL_MANAGERA, PRZYCHYLNOSC_MANAGERA, DOBRY_FEEDBACK_LUDZIE,
        SILA_SPRAWCZA_PRACA, SILA_SPRAWCZA_ULICA, REALNY_WPLYW_NA_WYDARZENIA, REALNY_WPLYW_NA_LUDZI, NIEOGLADA_SIE_NA_KONKURENCJE,
        WNIOSKI_HISTORIA, WNIOSKI_DOSWIADCZENIA, TRAFNE_DECYZJE, SIEDZENIE_MIEJSCA_RESTRYKCYJNE, SIEDZENIE_OSOBY_RESTRYKCYJNE,
        PODNOSZENIE_CIEZAROW, SILNE_UDERZENIE, ZAPASY, SILNI_KUMPLE_ZDOLNI_DO_WALKI,
        UNDERDOG, OD_ZERA_DO_MILIONERA_PRZEZ_CIERPIENIE, ANTY_FOLWARK, NAJWIEKSZA_WIEDZA_STOPIEN_PO_STOPNIU,
        SWIADOMOSC_PIENIADZ_NIC, SWIADOMOSC_SILA_SPRAWCZA_DUZO, MATERIA_DUZO, OKAZJA_DUZO, LOKALNOSC_DUZO,

        WIEK, CZY_CWEL, ODMOWA, BLISKOSC_70PROC, MALO_CZASU, NIE_ODZYWA_SIE, BRAK_SONDY,
        MILY_TEAMT, ZARTY, POCHWALA, DOBRE_EMOCJE, DOBRA_ROZMOWA, PIERWSZA_REAKCJA, REAKCJA_PO_SONDZIE, REAKCJA_PO_NARADZIE,
        DOBRE, TEGO_CO_RUCHA, KOBIETA_W_ZWIAZKU, NAPEWNO_DAJE, PRAGNIENIE_ZLA, NASTAWIENIE_NA_ZLO, SONDA_POD_ZROBIENIE_ZLA, BOJKA, W_CIEBIE,
        CIEKAWOSC_LUDZI, CIEKAWOSC_NIE_DEFAULTOWYCH_SYTUACJI, ATRAKCYJNOSC_ULICY,
        DOSTRZEZENIE_OKAZJI, NASTAWIENIE, ZAMKNIECIE_SYTUACJI, PRZEWAGA_MIMO_BLEDU, GLEBOKO_SZUKA_ZLA,  ZACHETA_DO_ZLA,
        OTWARTE_STARCIE, GLOSNO_CISNIECIE, FOTY, ZOBACZENIE_WARTOSCI, NIEDANIE_WYBORU, OSIAGNIECIE_WARUNKU,
        BOKS_DLUGOTRWALY, UZALEZNIENIE_OD_SPORTU, OSOBA_ZASIEG_WZROKU, SONDA_PO_WADACH,
        SIEDZENIE_MELINY, PRZYCHYLNOSC, NIE_ODKRYTY, UMNIEJSZANIE_WAD, WZAJEMNE_WSPARCIE, NIE_ODKRYCIE_WAD,
        NIEDOJEBANIE_UMYSLOWE,NIEDOJEBANIE_FIZYCZNE, TRAKTUJA_SIE_JAK_DZIECI, ZMAGA_SIE_WRAZLIWE_EMOCJE_NERWY_PARALIZ,
        AKTYWNA_KONTRA, OSZUKANIE_WDUPCENIE, PRZYJEMNOSCI, ZLE_W_ZYCIU, ROBI_GORZEJ_INNYM,
        ZASOBY_OGRANICZONE, SPRZECIW_WZGLEDEM_ZLA, CALE_ZLO_W_CIEBIE, WALI_OSOBE_BEZ_PRZEWAGI, NIE_ZATRZYMA_SIE,
        DZIALANIE_POZA_RANGA, ZAMKNIJ_ZASOB, Z_KIM, GDZIE,
        ZNAJOMOSC_FESTOW, ROZWALENIE_KOLKA_ADORACJI, ZNAJOMOSC_RDZENNYCH, ZNAJOMOSC_SLABYCH, NIEBOI_SIE_WYROKU,
        PSYCHO, BRAK_SENSU, USTALA_ZASADY, ODCIECIE_DOSTEPU_WARTOSC, ZNISZCZ_WARTOSC, ROB_STARTE, ZABURZ_SPOKOJ,
        GRZEBANIE_W_KIBLU_CODZIEN, MALY_ODZEW_SZUKANIE_PRACY, JEBANIE_PRZEZ_MANAGEROW_ZAWSZE, NIEMOZESZ_WYDAC_KASY,
        NIESPRAWIEDLIWE_PRZEWAGI, ODRAZU_ZLO, WIDZIAL, PRZEJEBANOSC_REGIONU, PRZYDUPASZENIE, NIENAWISC,
        ZMATERIALIZOWANIE_ZLA, WBICIE_NA_MUKE, WYKORZYSTANIE, /*ROBIENIE_CIERPIENIA*/ CIEZKIE_RANY, NIESPRAWIEDLIWOSC,
        BOI_SIE_BOGA, IDZIE_W_PRAWO, IDZIE_W_LEWO, SONDA_ZASOBU, TRUDNOSC_UTRZYMANIA, SONDA_DZIALANIA, EFEKTYWNOSC,
        DEFAULT_REAKCJA_ZLO, ZNIECZULICA, DEFAULT_REAKCJA_DOBRO, ZNISZCZYC, TEORIA_RYWALIZACJI,
        CHODZI_Z_BYLEKIM, BYLE_BEZPIECZENSTWO, BYLE_EMOCJE, PRZEWAGA_ZE_ZLA_OD_ROBIENIA_ZLA, ZYSK_Z_DZIALANIA,
        CHEC_KRZYWDY, NIEZWRACA_UWAGI_NA_KRZYWDE_INNYCH, ODRAZU_DZIALANIE, OSOBY_KAZDY_NA_KAZDEGO,
        OKAZJA, ZAGADANIE, PRZEGADANIE, LEKCEWAZY_INNYCH, WIDZISZ_ZLO, ODRAZU_DZIALANIE_KONTRA, GIERKA_KTO_NAJBARDZIEJ_PRZEJEBANY,
        KTOS_SAM, KTOS_PATRZY, KTOS_POSIADA, TEMAT_ZGODNY_Z_WARTOSCIAMI, TEMAT_ZGODNY_Z_EMOCJAMI, TEMAT_NIEPODWAZALNY,

        SPOTKANIE_WZROKIEM, KTO_WIECEJ_PATRZY, KTO_WIECEJ_CISNIE, KTO_WIECEJ_BIJE, KTO_WIECEJ_SPRZETU, KTO_WIECEJ_OSOB,
        KTO_WIECEJ_KONTUZJI, KTO_WIECEJ_STRACHU, RYZYKO, UKLADZIK, DASZ_SIE_POZNAC, NIESLUCHASZ, KOLEJNE_NIESPRAWIEDLIWE_PRZEWAGI,

        LATWY_CEL, MALA_SZANSA_POZNANIE, UNIZA, WSZYSCY_CHCA_CIE_ROZJEBAC, HASELKO, STATUS_QUO,
        WYKONYWANIE_ROZKAZOW_DLA_HAJSU_ZLA, /*WYROK,*/ OGRANICZONE_INFORMACJE,
        ROB_NAJWIEKSZA_KRZYWDE, ROZPOWIEDZ_DO_NAJWIEKSZEJ_LICZBY_OSOB, PRZEKONAJ_NAJWIECEJ_OSOB,
        DWA_TYGODNIE,

        ZADEMONSTROWANIE_WIEDZY, SZUKA_GLEBOKO_ZAGADNIEN, LICZY_KAZDY_BLAD, JA_NAJWAZNIEJSZY, AGRESJA_W_DZIALANIU,
        TO_CO_UMIESZ, TO_CZEGO_NIEUMIESZ, OCENA_ZE_STUDIOW, DOBRZE_NAPISANE_CV, WOLNE_MIEJSCE, ARTYKULY, KSIAZKI, PYTANIA_INTERVIEW,
        PROBA, ZDOBYCIE_PRACY, STRACONA_SZANSA, NOTA, WYSILEK_NA_DARMO, STRES_NA_DARMO,
        DOBRE_WYKONANIE, _0, ZLE_WYKONANIE, ZLY_FEEDBACK, ZLY_MIDYEAR, IMPROVEMENT_PLAN, ZAMKNIECIE_DOZYWOTNIE, BRAK_MOZLIWOSCI_POPRAWY,
        ZLEC_NIESZCZEGOLOWO, DAJ_MALO_ROBOTY, PRETENSJE, MANAGER_LUBIE, MANAGER_NIELUBIE, ZLEC_SZCZEGOLOWO,

        GRUPA_PRZESTEPCZA, DOBRA_PRACA, WAKACJE_WODA,

        POSLUSZNY_SILE, UZNAJE_HIERARCHIE, ODDANIE_SIE_ZA_PIENIADZE, BRAK_WSTEPU_RDZENNI, LECZY_KOMPLEKSY_W_PRACY,
        TWARDOGLOWOSC, DUZO_OBOWIAZKOW, MNIEJ_NIZ_2_LATA_DOSWIADCZENIA, WIECEJ_NIZ_2_LATA_DOSWIADCZENIA,
        DOBRZE_JEZELI_UMIE, MUSI_UMIEC_WSZYSTK0,

        NASTAWIENIE_AGRESJA, NASTAWIENIE_KONTEMPLACJA, NASTAWIENIE_PRACA,
        NASTAWIENIE_OSZUKANIE_WDUPCENIE, NASTAWIENIE_DOBRO, NASTAWIENIE_POZNANIE, NASTAWIENIE_KONTRA,
        NASTAWIENIE_PRZYJEMNOSCI, NASTAWIENIE_AGRESJA_W_DZIALANIU, NASTAWIENIE_WSPARCIE, NASTAWIENIE_PRZECIW,

        ENERGETYKA,

        NOTYFIKACJA_EKIPA, ROZKMINIA, WSPARCIE_OSLONY,

        WYKOLEJONY, WIESNIAK, NORMALNY, OSIEDLOWY_MOCNY,

        PRIORYTET,

        MELINA_NA_OSIEDLU, GLOWNA_DROGA, WROGOSC, SLEPA_LOJALNOSC, BRAK_SUPERPOZYCJI, NIEWOLNIK, TWOJE_ZDANIE_NIC_NIE_ZNACZY,
        MIEJSCE_ZAMIESZKANIA, CZYSTE_SUMIENIE, BRAK_NUDY, WYJSCIE_NA_ULICE,

        BLEDNY_SYSTEM_WARTOSCI, MALO_WAZNE_MOCNO, WAZNE_SLABO,

        NASTAWIENIE_MAM_ZLE_ON_TEZ_MUSI, NASTAWIENIE_NIE_MAM_NIC_ON_TEZ_MA_NIE_MIEC, NASTAWIENIE_JA_GNOJONY_GNOJE_NIZSZYCH,
        NASTAWIENIE_DOMINACJA,

        SIEDZENIE_W_SRODOWISKU, STREFA_KOMFORTU, POTRZEBA_EMOCJI, ZNUDZENIE_OSOBAMI, POTRZEBA_NOWYCH_OSOB,

        NIESTARANIE_SIE, NIC_OD_SIEBIE, PRZYJSCIE_NA_GOTOWO, SONDA_ILE_MOZNA,

        ZWOLNIENIE, SPRAWA_W_SADZIE,

        NIE_ZNAM, DRUGA_STRONA, NIE_MA_DOSTEPU, ROZKMINIC, NAJWIEKSZA_KRZYWDA, DZIALANIE_DLA_ZLA, BRAK_DOSTEPU_RDZENNI,

        BUDZET, POTRZEBA_AUTOMTAYZACJI,
        LAMUS, /*KOBIETA*/ DUZO_OSOB, DOSTEP_RESTRYKTOWANY, Z_KOBIETA,

        MORALNIAK, STRATA_MANIURY, CHEC_POMSZCZENIA, WPIERDOL,
        GNOJENIE, PRACA_PO_ZNAJOMOSCI, DO_KOSZA, POLOZENIE_SIE_PRZED_DZIALAJACYM,
        NAGADYWANIE_KOLEZANEK, SZUKA_KANDYDATOW_ZROBIENIE_ZLA, STWARZA_OKAZJE_ZROBIENIE_ZLA,

        FOTY_MIEJSCE_STALE, NIE_MILA_OBSLUGA, ZLE_WYKONANIE_USLUGI, OGRANICZENIE_WOLNOSCI,

        CZARNE_WLOSY, TATUAZE, DRESY_SZARE_MATERIALOWE,
        PATRZY_ZLE, PATRZY_Z_EXSTAZA, PATRZY_JAKBY_CHCIAL_OKLAMAC, SLABA_POSTURA, PRZEWIDUJE_ZLE,
        NIE_PATRZY_ALE_KONSULTUJE,
        KASZLE, MACHA, GWIZDZE, ZADAJE_GLUPIE_PYTANIA, TELEFON_ZDJECIA, ZABRAC_COS,

        ZROBIONE_ZLO, CZEKA_NA_EFEKT, BRAK_REAKCJI, ZAPRZESTANIE_ZLA, WYLACZENIE_DZIALACZA,

        CHRONICZNE_BEZROBOCIE, NISKIE_PENSJE, ZMYSLY_DLA_ZLA, WYWYZSZENIE_SLABYCH, NASTAWIENIE_HIERACHI_PRZYWILEJE,
        INFORMACJE, ZERO, BRAK_ZDROWIA, PIEKLO, ZNISZCZENIE_WARTOSCI_MATERIALNEJ, GORA, _1_RUCH,
        DUZY_WYSILEK, /*MALY_WYSILEK*/, BRONI_SIE, NAJWIEKSZ_STRACH, UCIECZKA, ODPOWIADA, TWOJA_PORAZKA, JESTES_SILNY,
        WYKRECENIE,

        RUDY, RUMUN, CZERWONE_OCZY, GAZ, TORBA, LEKKI_GLOS, DZIWNY_GLOS, SLABO_REAGUJE_NA_BODZCE, CHLOPAK,
        KLUCENIE_RODZINY, DAZENIE_DO_ZLA, SZUKANIE_GLEBOKO_ZLA, ZAMACH_NA_ZYCIE,
        KAZDE_DZIALANIE_ZMIENIA_W_ZLO,

        SLEPE_DZIALANIE, KROTKOWZROCZNOSC, REAKACJA, UKAZANIE, _80_PROCENT_CHCE_CIE_ROZJEBAC, WIEKSZOSC_DZIALA,
        CHETNOSC_ZERO, DZIALAJACE_KARYNY, NIEMOZLIWOSC_PODERWANIA_KOBIETY_NEUTRALNY_RZUT, NIEMOZLIWOSC_ZDOBYCIA_PRACY_NEUTRALNY_RZUT,
        PODJECIE_WALKI, /*GAZ*/ OSTRY_SPRZET, ROBIENIE_PRZYPALU,

        ZERO_TOLERANCJI_DZIALAJACY, OKRASC_PIENIADZE, NOTYFIKACJA_ALL_O_HANBIE, DZIALANIE_POD_PRESJA, BRAK_UKLADOW,
        CECHY_WRODZONE, POPED_SEXUALNY, MARZENIA, OCZEKIWANIA_WOBEC_ZYCIA, PRZEWAGI_OD_KOLYSKI, PRZYJEMNOSCI_OD_KOLYSKI,

        WADY_FIZYCZNE, WADY_UMYSLOWE,
        ROZWOJ_UMYSLOWY, ROZWOJ_FIZYCZNY, MOZE_CZYMS_BLYSNIE, ZLE_ZAMIARY, ZNISZCZENIE,

        SUKCES, NIESWIADOMOSC_OPPONENTA, MIEJSCE_STALE_DZIALAJACE, KRZYWDA_DRUGIEJ_STRONY,
        WESELE, CHCEMY_WIECEJ, ZA_CIOSEM, NORMALNOSC,
        SWOI, ZLI, SZKODLIWY_WPLYW,

        UMNIEJSZENIE, USPRAWIEDLIWINIE, UKAZANIE_W_PRAWDZIE, SPOGLADANIE_NA_SIEBIE,

        TOLEROWANIE_ZLA, POZWOLENIE_NA_ZLO, SLUCHANIE_ZLEGO, PELNE_POPARCIE_ZLA,
        CEL_ATAKU, SLABSI, POSTAWIENIE_CIEZKICH_WARUNKOW, ZNISZCZENIE_PRZEWAGI, FALSZYWE_WRAZENIE, WYSOKIE_OCZEKIWANIE,
        ATAK_NA_CZLONKOW_RODZINY, DYSTANS, LEKCEWAZENIE,  PYCHA, ZUCHWALOSC, POCZUCIE_WYZSZOSCI,

        WARTOSC_MATERIALNA, MONOPOL_ZLA, POTRZEBA_WSPARCIA, POTRZEBA_AKCEPTACJI, ULTIMATUM_OD_SILNIEJSZYCH, POTRZEBA_PARTNERA,

        DOBRO_W_SERCU, CIERPIENIE_OD_ZLYCH, ZLY_OWOC, STRATA_SIL, DUZA_KRZYWDA_NA_PRZEWADZE, GRZEBANIE_PRYWATNE,
        WYCHODZENIE, DUZA_PRZEWAGA,
        DZIALA, BIEGA, SLUCHAJA, OBECNOSC_LUDZI, OSOBA_POZA_SRODOWISKO, BYCIE_LEPSZYM, SLABOSC, WYCHODZENIE_NA_ULICE,
        POMSZCZENIE, OBRAZENIA_FIZYCZNE, STARCIE_WIELU_NA_JEDNEGO, WYCHODZENIE_U_SIEBIE, RZECZY_WARTOSCIOWE, NIESWIADOMY,
        PRZEWAGA_NA_BRAK_PRZEWAGI, STRATA_ZNAJOMYCH, POSLUCH, NIE_ODBIERANIE_TELEFONU, WYPOMNIENIE_HANBY,
        IDZIESZ, STOISZ_BRAMA, STOISZ_MIEJSCE_STALE, JEDZIESZ_TRAUTO, DANIE_ZYCIA, CZYNIENIE_SWIATA_LEPSZYM,
        CZYNIENIE_SWIATA_GORSZYM,

        POGODA, SLUZBA_ZROWIA, USLUGI, EVENTY, AKTUALNE_WYDARZENIA_SWIATA, NOWE_TECHNOLOGIE, KULTURY_SWIATA,
        GOTOWANIE,

        MELANZ, STANDARD_ZACHOWANIA, PYTANIE,

        RDZENNY, FIRMA, SWIAT, _1_VS_1_STARCIE_BEZ_PRZEWAG, KSIAZKA, SPIS_TRESCI, BUZZWORDY, ARTYKUL, GITHUB,

        // OPERATORY
        _II_, _88_, _NOT_
}
