package warunek;

/**
 * Created by gadzik on 22.12.19.
 */
public enum Warunek {
        // *** *** *** *** *** *** *** *** *** WSTEPNE *** *** *** *** *** *** *** ***

        // SWIAT
        ZWIAZEK_2_OSOB, URODZENIE_SIE, ZDROWIE, BYT_MATERIALNY,

        // INFORMACJA
        CZAS, DOSTEP_DO_PLANSZY, LUDZIE, MATERIALNE_ZNALEZIENIE_SIE, SONDA, SZCZEGOLY,

        // WIEDZA
        INFORMACJA, PRZYCZYNA, SKUTEK, WNIOSKI,

        // BRAK_WSTYDU
        /* INFORMACJA,*/  WIEDZA, DZIALANIE,

        // REZULTAT
        /* DZIALANIE,*/ KONSEKWENCJE, /*WNIOSKI,*/ REZULTAT,

        // PRACA
        NIEKARALNOSC, WYKSZTALCENIE, DOSWIADCZENIE, UMIEJETNOSCI, ZNAJOMOSCI,

        // PRACA RESTRYKCYJNA
        /*NIEKARALNOSC,*/ STUDIA, KILKA_LAT_DOSWIADCZENIA, WIELE_UMIEJETNOSCI, Z_POLECENIA,

        // ZARABIANIE
        UMOWA_PRACA, WYKONYWANIE_PRACY,

        // SPORT
        /*CZAS,*/ SPRAWNOSC, ZDOLNOSC_DO_WYSILKU, EKWIPUNEK, ZGODA_OTOCZENIA,

        // OSIEDLE
        TO_SAMO_MIASTO, DOBRZE_WYGLADA, ZNAJOMY_W_SRODOWISKU,
        NIE_PRZECIWNY, NIE_KONFI,

        // DOPUSZCZENIE
        PATRZY, REAGUJE, USMIECHA, DOBRO,
        KOJARZY, KTORYS_RAZ, WSPOLNI_ZNAJOMI,
        BEZPIECZENSTWO, NUDA, PODOBA_SIE,
        MUSI_DOPUSCIC,

        // KOBIETA
        STWORZENIE_POINTCUTA,
        ZLAPANIE_POINTCUTA,
        POZNANIE,
        DOPUSZCZENIE,
        PARZONKO_XKILKA, SPODOBANIE_SIE,
        PLUS_GT_MINUS, WOLNA,

        // *** *** *** *** *** *** *** *** *** WSTEPNE *** *** *** *** *** *** *** ***

        // *** *** *** *** *** *** *** *** *** UTRZYMANIA *** *** *** *** *** *** *** ***

        // SWIAT
        ZNAJOMI, SWOJ_ZWIAZEK, UNIKANIE_ZAGROZEN, DBANIE_ZDROWIE, ZARABIANIE,

        // INFORMACJA
        SLEDZENIE_INFORMACJI, REZULTAT_INFORMACJI, POTWIERDZENIE_Z_KIMS, SPRAWDZENIE_SAMEMU,

        // WIEDZA
        ODSWIEZANIE, PAMIEC, ULEPSZANIE, DZIELENIE_SIE_WIEDZA,

        // BRAK_WSTYDU
        LEPSZE_WYKORZYSTANIE_INFORMACJI, LEPSZE_DZIALANIE, /*WNIOSKI,*/

        // REZULTAT
        /* LEPSZE_DZIALANIE,*/ UNIKNIECIE_KONSEKWENCJI, PRZEWIDYWANIE, /*REZULTAT,*/ UTRZYMANIE,


        // PRACA
        /*WYSILEK, UZYTECZNOSC, OPLACA, PLUS_GT_MINUS,*/

        // ZARABIANIE
        BOGATY_SEKTOR, /*WIEDZA,*/ NISZA, REGION,

        // PRACA RESTRYKCYJNA
        PRZESTRZEGANIE_ZASAD, ATMOSFERA, WYSILEK, UZYTECZNOSC, REZULTATY, OPLACA, STOSUNEK1VS1, ULEPSZANIE_UMIEJETNOSCI, /*PLUS_GT_MINUS,*/

        // SPORT
        /*CZAS, SPRAWNOSC, ZDOLNOSC_DO_WYSILKU, EKWIPUNEK, ZGODA_OTOCZENIA,*/

        // OSIEDLE
        CZESTO_Z_CELEM, /*DZIALANIE,*/ ZACIESNIENIE_GRONA_ZNAJOMYCH,
        STO_PRO_LOJALNY, /*PRZESTRZEGANIE_ZASAD,*/

        // DOPUSZCZENIE
        DOBRZE_ZNA, /*WSPOLNI_ZNAJOMI,*/
        /*BEZPIECZENSTWO,*/ EMOCJE, /*PODOBA_SIE,*/
        /*PLUS_GT_MINUS,*/

        // KOBIETA
        /*PLUS_GT_MINUS, ZGODA_OTOCZENIA,*/
        SPELNIENIE_OCZEKIWAN,
        WSPIERANIE_PREFERENCJI,
        ODKRYWANIE_SWIATA,
        SPEDZANIE_CZASU,
        WIERNOSC,

        PILNOWANIE, KONTROLA,

        // *** *** *** *** *** *** *** *** *** UTRZYMANIA *** *** *** *** *** *** *** ***

        // KONCOWE
        SZCZESCIE, DOSWIADCZENIA, WSPOMNIENIA,
        /*ZNAJOMI,*/
        KOBIETA, DZIECI,
        /*PIENIADZE, BEZPIECZENSTWO,*/ STABILIZACJA, POZOSTANIE_W_KRAJU, /*ULEPSZANIE_UMIEJETNOSCI,*/
        MOZLIWOSC_WYBORU,
        /*SPRAWNOSC,*/ SILA,
        SILNE_JEDNOSTKI, OSZCZEDNOSC_CZASU, AKCEPTACJA, LATWY_DOSTEP_PRZEWAGI,
        CODZIENNA_BLISKOSC, ZYCIE_RAZEM,

        // PRZYCZYNY ZLA
        ZLE_GENY, GLUPOTA, NARKOTYKI, NIESWIADOMOSC, DZIALANIE_ZA_NAMOWA,

        // WARTOSC
        WYGODY, ROZRYWKI, PIENIADZE, SRODOWISKO, ZASADY, /*UMIEJETNOSCI,*/ IDEA, NAUKA, SPORT, WSPIERANIE_SWOJEJ_KLASY,
        MODA, BECZKA, KOLEZANKI, WRAZLIWOSC, /*DZIECI,*/ CHLOP, RODZINA,

        // GLOBAL PLANSZA
        /*LUDZIE,*/
        DZIETNOSC, WYCHOWANIE, MIESZKANIE,

        PRACA,
        FIRMY_NIEWYMAGAJACE_DOSWIADCZENIE, FIRMY_WYMAGAJACE_DOSWIADCZENIE, RYNEK_PLAC, ZASOBY_LUDZKIE,

        MIEJSCA,

        // OCENIA WG
        ZLO, /*DOBRO,*/ ZYSK, EKIPA, PRZEWAGA, UMIEJETNOSC, PODOBIENSTWO,

        // THREAD WHILE LOOPS
        THREAD_WHILE_LOOP_BLISKOSC_K, THREAD_WHILE_LOOP_ZASIEG_WZROKU,
        THREAD_WHILE_LOOP_EFEKTYWNA_GADKA,

        THREAD_WHILE_LOOP_BLISKOSC_U,

        // PRZEWAGI
        /*ZNAJOMI,*/ OSIEDLOWE_SRD, /*KOBIETA,*/
        SZANSA_ZNAJOMI, SZANSA_OSIEDLOWE_SRD, SZANSA_KOBIETA,
        /*INFORMACJA, CZAS, WIEDZA,*/ BRAK_WSTYDU,
        LUDZIE_ZA_TOBA, WALKA_PIESCI, WALKA_SPRZET,
        /*UMIEJETNOSC,*/
        /*PRACA, PIENIADZE,*/
        WYSOKA_POZYCJA,
        SPRYT, SZYBKOSC, PRZEZYCIE_CIERPIENIA, SILNY, POTRAFI_OCENIC,

        // SLABOSCI
        /*BRAK_ZNAJOMYCH, BRAK_SRODOWISKA, BRAK_KOBIETY,*/
        BRAK_SZANS_ZNAJOMI, BRAK_SZANS_SRODOWISKO, BRAK_SZANS_KOBIETA,
        /*BRAK_INFORMACJI, BRAK_CZASU, BRAK_WIEDZY,*/ WSTYD,
        BRAK_LUDZI_ZA_TOBA, NIEZDOLNY_WALKA_PIESCI, NIEZDOLNY_WALKA_SPRZET,
        /*BRAK_UMIEJETNOSCI,
        BRAK_PRACY, BRAK_PIENIEDZY,*/
        SLABA_POZYCJA,
        TEMPOTA, POWOLNY, PRZEZYCIE_WYGOD, PRZEZYCIE_DOBRA, SLABY, NIEUMIE_OCENIC,

        // CIERPIENIE
        ZMECZENIE, CIERPIENIE_FIZYCZNE, CIERPIENIE_PSYCHICZNE, CIERPIENIE_PRZEMIJANIA, CIERPIENIE_UTRATY,
        CIERPIENIE_SAMOTNOSCI, CIERPIENIE_WIDZENIE_BRAK_DOTKNIECIA,
        ZMECZENIE_DLUGOTRWALE, CIERPIENIE_FIZYCZNE_DLUGOTRWALE, CIERPIENIE_PSYCHICZNE_DLUGOTRWALE,
        CIERPIENIE_PRZEMIJANIA_DLUGOTRWALE, CIERPIENIE_UTRATY_DLUGOTRWALE, CIERPIENIE_SAMOTNOSCI_DLUGOTRWALE,
        CIERPIENIE_WIDZENIE_BRAK_DOTKNIECIA_DLUGOTRWALE,


        // ZAGROZENIA
        STRATA_WOLNOSCI, STRATA_CZASU, STRATA_INFORMACJI, STRATA_WIEDZY,
        STRATA_DOSTEPU_PLANSZA, STRATA_DOSTEPU_ZNAJOMI, STRATA_MIEJSCA_W_HIERARCHII, STRATA_POZYCJI,
        STRATA_ZDROWIA, STRATA_HONORU,
        STRATA_PRACY, STRATA_PIENIEDZY, STRATA_ZARABIANIA, STRATA_WYKSZTALCENIA,
        STRATA_KOBIETY, ROZWOD, ALIMENTY,

        // ZASADY
        PRAWO, /*NIE_KONFI,*/ NIE_PRZECIWNA, NIEZNAJOMY_JEBAC,
        NIEGADAJ_Z_OBCYMI, NIEGADAJ_Z_POZAOSIEDLA, NIEGADAJ_Z_NIESLAZAKAMI,
        KTO_NIEBIEGA_TUBA,
        JEDNOSC_PRZECIW_ZAZDROSCI,
        R1_HOLD_YOUR_POSITION, R2_YOU_ONLY_GOT_ONE_CHANCE_TO_SCORE, R3_LIFE_IN_YOUR_HANDS_NOT_LORDS,
        R4_WATCH_YOUR_ACTIONS,

        // POTRZEBA
        KONTAKTU, AKCEPTACJI, DOBRYCH_JEDNOSTKEK, ZWIAZKU, ZROZUMIENIA, HIGIENY, UBRANIA, RELIGII, /*ROZRYWKI,*/ RUCHU,
        // PRZYMUS
        JEDZENIE, PICIE, /*PRACA,*/ EDUKACJA, PRZEMIESZCZANIE_SIE, TRANSPORT, KUPNO_PRODUKTOW,
        // NIESPRAWIEDLIWOSC
        PRACA_XCZASU_BRAK_REZULATU, WDUPCANIE_WYSILKU_DO_PIECA, NADUZYWANIE_WYSOKIEJ_POZYCJI, GORZEJ_NA_STARCIE, PRZEWAGA_NA_STARCIE,
        STRONNICZOSC, WYKLUCZENIE,


        // DOBRY
        ROBIENIE_PROGRESU, ZDOBYWANIE_UMIEJETNOSCI, ZDOBYWANIE_WIEDZY, ZDOBYWANIE_SILY, USWIADAMIANIE,
        WYCIAGANIE_ZE_ZLEJ_SYTUACJI, ZMNIEJSZANIE_ZLA, ROBIENIE_OPCJI, PRZEKONYWANIE_ZA, POLECENIE,
        PRAWDA, CIERPLIWOSC,
        TRZEZWOSC,
        MADROSC,
        NOWY_DEFAULT_DOBRA_OSOBA,
        NIEPOZWALA_NA_ZLO,

        // ZLY
        MARNOWANIE_CZASU, POZBAWIANIE_UMIEJETNOSCI, POZBAWIANIE_WIEDZY, POZBAWIANIE_SILY, OGLUPIANIE,
        WDUPCANIE_W_ZLE_WARUNKI, ZAMYKANIE_OPCJI, PRZEKONYWANIE_PRZECIW,
        KLAMSTWO, AGRESJA_FIZYCZNA, AGRESJA_PSYCHICZNA,
        ODUZENIE,
        /*GLUPOTA,*/
        NOWY_DEFAULT_RYWAL,
        JEBIE_DOBRO, WYMAGA_PRZEWAG_NA_ZLU,

        // WYMUSZENIE REAKCJI
        KONTEKST, OSKARZENIE, ULTIMATUM, CISNIECIE,

        // REAKCJA
        BRAK_ODPOWIEDZI, PRZESTRASZENIE_SIE, UCIECIE,
        ODPOWIEDZ_ODCZEP, ODPOWIEDZ_NEUTRAL, ODPOWIEDZ_ZAINTERESOWANIE,
        EKSCYTACJA, PRZEJCIE_INICJATYWY,

        // SONDA GDY
        WIDZISZ, MOWI, ROBI, POSIADA,

        // SONDA PO
        OCZY, REAGOWANIE, CHODZENIE, POSTURA, ZACHOWANIE, MOWA, /*ZNAJOMI,*/

        // KRYTERIA WROGA
        PRZECIWNA_RASA, PRZECIWNY_NAROD, PRZECIWNA_KLASA, PRZECIWNY_KLUB, PRZECIWNA_STRONA, ZASZKODZIL,

        // PLAN
        CYKL_DNIA, DZIEN, TYDZIEN, MIESIAC, TRZY_MIESIACE, POL_ROKU, ROK,

        // ZART
        UKAZANIE_OSOBY_W_KOMICZNEJ_SYTUACJI, WYOLBRZYMIENIE, ZAMIANA, RZECZYWISTOSC_ODBIEGAJACA_OD_NORMY,

        // ERA
        PONIZEJ_1900, OD_1900_DO_1939, OD_1939_DO_1945, OD_1945_DO_1953, OD_1953_DO_1970,
        OD_1970_DO_1990, OD_1990_DO_2000, OD_2000_DO_2005, OD_2005_DO_2011, OD_2011_DO_2016, OD_2016_DO_TERAZ,
        // TODO: MOCNE JEDNOSTKI W KAZDEJ Z ER

        // ROZRYWKI
        MUZYKA, TANIEC, TELEWIZJA, GRY, PRZYJEMNA_ROZMOWA, /*ODUZENIE,*/

        // PRACA
        PRACA_ZAWODOWA, PRACA_SZTUKI_WALKI, PRACA_NAD_KOBIETA, PRACA_NAD_DZIECKIEM, PRACA_NAD_BRACMI,

        // ZMYSLY

        // EMOCJE NEGATYWNE
        STRACH, LEK, ADRENALINA, NIEPOKOJ, TESKNOTA, /*SAMOTNOSC,*/
        GNIEW, ZLOSC, ROZPACZ, SMUTEK,
        ZAZDROSC,
        /*AGRESJA_FIZYCZNA, AGRESJA_PSYCHICZNA*/

        // EMOCJE POZYTYWNE
        /*SZCZESCIE,*/ RADOSC, KONTEMPLACJA, SPELNIENIE, SPOKOJ,
        CIEKAWOSC, ZASKOCZENIE,
        PODNIECENIE,

        // UCZUCIA NEGATYWNE
        ZREZYGNOWANIE,
        POCZUCIE_UTRATY,
        PRZYKROSC, POCZUCIE_WYKLUCZENIA, ZAGROZENIE,

        // UCZUCIA POZYTYWNE
        MILOSC, PRZYJAZN, BRATERSTWO, KOLEZENSTWO, POCZUCIE_SZCZESCIA, POCZUCIE_ZYSKU, POCZUCIE_SUKCESU,
        ZAPAL, PRZYJEMNOSC,

        // ZDOBYWANIE WIEDZY
        /*OCZY, PRZYCZYNA, REZULTAT, WNIOSEK,*/ SLOWO_PISANE, DOWODY_TEORII_NA_PLANSZACH, SLYSZANE_SLOWA,

        // ZAROBEK NIELEGALNY
        DILLERKA, ZLODZIEJKA, PRZEMYT, JAZDA_ZE_SPRZETEM,

        // KURESTWO
        POLICJA, PUSZCZALSKOSC, ZDOLNOSC_KONFIDENTCTWO,

        // SYTUACYJNE
        /*PATRZY,*/ SIEDZI, Z_KOLEZANKA, WZGL_IZOLACJA,


// TODO MUZYKA ZAGRANICZNA, ZARCIE ZZAGRANICY ...
// TODO SZAJKA, LYSY










        // *** *** *** *** *** *** *** *** *** PATOLOGIE *** *** *** *** *** *** *** ***
// PATOLOGIE ZWIAZKU
        STARY_MLODY, BURZUA_ULICA, NIESWIADOMY_SWIADOMY, SLABY_MOCNY, UZYWKI_BRAKUZYWEK, ZLO_DOBRO,
        LEKKOSC_TRUDNOSC, LATWOSC_ZERWANIA, ZDRADA, BRAK_CZASU, ODLEGLOSC,

        // PATOLOGIE_WSTEPNE_SWIAT
        SAMOTNOSC, ZWIAZEK_HOMOSEXUALNY, USZCZERBEK_NA_ZDROWIU, BIEDA,

        // PATOLOGIE_WSTEPNE_INFORMACJA
        /*BRAK_CZASU,*/ BRAK_DOSTEPU_DO_PLANSZY, BRAK_LUDZI, NIEMOZLIWOSC_MATERIALNEGO_ZNALEZIENIA_SIE, BRAK_MOZLIWOSCI_OCENY,
        OGOLNOSC,

        // PATOLOGIE_WSTEPNE_WIEDZA
        BRAK_INFORMACJI, BEZ_PRZYCZYNY, ZLE_SKUTKI, NIE_WYCIAGANIE_WNIOSKOW,

        // PATOLOGIE_WSTEPNE_BRAK_WSTYDU
        BRAK_WIEDZY, BRAK_DZIALANIA,

        // PATOLOGIE_WSTEPNE_REZULTAT
        OGROMNE_KONSEKWENCJE, BRAK_REZULTATOW,

        // PATOLOGIE_WSTEPNE_PRACA
        KARALNOSC, BRAK_WYKSZTALCENIA, BRAK_DOSWIADCZENIA, BRAK_UMIEJETNOSCI, ZADNYCH_ZNAJOMOSCI,

        // PATOLOGIE WSTEPNE_ZARABIANIE
        BRAK_PRACY, BRAK_PIENIEDZY,

        // PATOLOGIE WSTEPNE_SPORT
        NIESPRAWNOSC, NIEZDOLNOSC_DO_WYSILKU, BRAK_ZGODY_OTOCZENIA,

        // PATOLOGIE WSTEPNE_OSIEDLE
        INNE_MIASTO, ZLE_WYGLADA, BRAK_ZNAJOMYCH_W_SRODOWISKU, PRZECIWNY, KONFI,

        // PATOLOGIE WSTEPNE_DOPUSZCZENIE
        NIE_PATRZY, NIE_REAGUJE, NIE_USMIECHA, /*ZLO,*/ NIE_KOJARZY, WIDZI_PIERWSZY_RAZ, BRAK_WSPOLNYCH_ZNAJOMYCH,
        NIEBEZPIECZENSTWO, ZAJECIE, NIE_PODOBA_SIE, BRZYDKA, WSTYDZI_SIE, BRAK_EMOCJI,

        // PATOLOGIE WSTEPNE_KOBIETA
        NIE_STWORZENIE_POINTCUTA, NIEZLAPANIE_POINTCUTA, BRAK_POZNANIA, NIEDOPUSZCZENIE, BRAK_PARZONKA,
        NIESPODOBANIE_SIE, MINUS_GT_PLUS, ZAJETA,

        // PATOLOGIE UTRZYMANIA_SWIAT
        BRAK_ZNAJOMYCH, BRAK_ZWIAZKU, ZAGROZENIA, BRAK_ZRODLA_ZAROBKU,

        // PATOLOGIE UTRZYMANIA_INFORMACJA
        ZNIKNIECIE_INFORMACJI, BRAK_REZULTATU_INFORMACJI, BRAK_POTWIERDZENIA, NIEMOZLIWOSC_SPRAWDZENIA,

        // PATOLOGIE UTRZYMANIA_WIEDZA
        ZAPOMNIENIE, REGRESS_WIEDZY, UKRYWANIE_WIEDZY,

        // PATOLOGIE UTRZYMANIA_BRAK_WSTYDU
        NIEWYKORZYSTYWANIE_INFORMACJI, /*BRAK_DZIALANIA, NIE_WYCIAGANIE_WNIOSKOW,*/

        // PATOLOGIE UTRZYMANIA_REZULTAT
        NIE_PRZEWIDYWANIE, UTRACENIE,

        // PATOLOGIE UTRZYMANIA_PRACA
        BRAK_WYSILKU, NIE_UZYTECZNOSC, NIE_OPLACA, /*MINUS_GT_PLUS,*/
        NIE_PRZESTRZEGANIE_ZASAD, ZLA_ATMOSFERA, /*BRAK_REZULTATOW,*/ ZLE_STOSUNKI1VS1,
        REGRESS_UMIEJETNOSCI,

        // PATOLOGIE UTRZYMANIA_ZARABIANIE
        BIEDNY_SEKTOR, /*BRAK_WIEDZY,*/ DUZA_KONKURENCJA, BIEDNY_REGION,

// PATOLOGIE UTRZYMANIA_SPORT
        /*REGRESS_UMIEJETNOSCI,*/

        // PATOLOGIE UTRZYMANIA_OSIEDLE
        BRAK_CELU, NIE_DZIALA, NIE_KIBICUJE, NIELOJALNY, NIE_PRZESTRZEGA_ZASAD,

        // PATOLOGIE UTRZYMANIA_KOBIETA
        NIESPELNIENIE_OCZEKIWAN, NIEWSPIERANIE_PREFERENCJI, SPEDZANIE_CZASU_OSOBNO, /*ZDRADA,*/ BRAK_KONTROLI,

        // PATOLOGIE KONCOWE_SWIAT
        NIESZCZESCIE, ZLE_DOSWIADCZENIA, ZLE_WSPOMNIENIA,

        // PATOLOGIE KONCOWE_PRACA
        /*BRAK_PIENIEDZY,*/ BRAK_STABILIZACJI, ZMUSZONY_ZAGRANICA, /*BRAK_UMIEJETNOSCI, BRAK_WIEDZY,*/

        // PATOLOGIE KONCOWE_ZARABIANIE
        BRAK_MOZLIWOSCI_WYBORU,

// PATOLOGIE KONCOWE_SPORT
        /*NIESPRAWNOSC, BRAK_UMIEJETNOSCI, BRAK_WIEDZY,*/

        // PATOLOGIE KONCOWE_OSIEDLE
        /*BRAK_ZNAJOMYCH,*/ BRAK_SRODOWISKA, BRAK_KOBIETY, BRAK_DOSTEPU_SILNE_JEDNOSTKI,
        BRAK_THREAD_WHILE_LOOP_BLISKOSC_U, /*MARNOWANIE_CZASU,*/ BRAK_AKCEPTACJI, BRAK_DOSTEPU_PRZEWAGI,

        // PATOLOGIE KONCOWE_KOBIETA
        BRAK_CODZIENNEJ_BLISKOSCI, ZYCIE_W_SAMOTNOSCI, BRAK_DZIECI, PRZERWANIE_GENU,

        // PATOLOGIE GLOBAL_PLANSZA_LUDZIE
        MALA_DZIETNOSC, BLEDY_WYCHOWANIA, BRAK_MIESZKANIA,

        // PATOLOGIE GLOBAL_PLANSZA_PRACA
        BRAK_FIRM_NWD, BRAK_FIRM_WD, ZABURZONY_RYNEK_PLAC, OGROMNE_ZASOBY_LUDZKIE,

        // PATOLOGIE THREAD_WHILE_LOOP
        BRAK_THREAD_WHILE_LOOP_ZASIEG_WZROKU, /*BRAK_THREAD_WHILE_LOOP_BLISKOSC_U,*/
        BRAK_THREAD_WHILE_LOOP_BLISKOSC_K, BRAK_THREAD_WHILE_LOOP_EFEKTYWNA_GADKA,


// todo nieprzerwana gadka, od czasu do czasu angaz&check
}
